// Package instructorsapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package instructorsapi

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for ErrorCode.
const (
	ErrorCodeAlreadyCancelled       ErrorCode = "already_cancelled"
	ErrorCodeBadRequest             ErrorCode = "bad_request"
	ErrorCodeDoubleBooking          ErrorCode = "double_booking"
	ErrorCodeForbidden              ErrorCode = "forbidden"
	ErrorCodeIdempotencyKeyConflict ErrorCode = "idempotency_key_conflict"
	ErrorCodeInternalError          ErrorCode = "internal_error"
	ErrorCodeInvalidCode            ErrorCode = "invalid_code"
	ErrorCodeNotFound               ErrorCode = "not_found"
	ErrorCodeSlotCancelled          ErrorCode = "slot_cancelled"
	ErrorCodeSlotFull               ErrorCode = "slot_full"
	ErrorCodeSlotStarted            ErrorCode = "slot_started"
	ErrorCodeTooManyRequests        ErrorCode = "too_many_requests"
	ErrorCodeUnauthorized           ErrorCode = "unauthorized"
)

// Error Стандартное тело ошибки.
type Error struct {
	// Code Канонический машинный код ошибки (R-023). Доменные коды: slot_full (нет свободных мест), double_booking (повторная бронь того же слота), slot_cancelled (слот отменён клубом), slot_started (слот уже стартовал), already_cancelled (бронь уже отменена), invalid_code (неверный/истёкший OTP). Идемпотентность: idempotency_key_conflict (повтор ключа с другим телом). Транспортные/общие: bad_request (400), unauthorized (401), forbidden (403), not_found (404), too_many_requests (429), internal_error (5xx).
	Code ErrorCode `json:"code"`

	// Details Необязательные машиночитаемые детали для динамических сообщений на клиенте (foundations §6): например, актуальная доступность для E1/E2, чтобы показать «Свободно: N мест» / «Свободно: M комплектов экипировки» без разбора текста message.
	Details *struct {
		// AvailableRentalGear Сколько прокатных комплектов экипировки реально свободно (для нехватки прокатных комплектов экипировки).
		AvailableRentalGear *int `json:"available_rental_gear,omitempty"`

		// AvailableSeats Сколько мест реально свободно на момент ошибки (для slot_full / превышения мест).
		AvailableSeats *int `json:"available_seats,omitempty"`
	} `json:"details,omitempty"`

	// Message Человекочитаемое сообщение об ошибке.
	Message string `json:"message"`
}

// ErrorCode Канонический машинный код ошибки (R-023). Доменные коды: slot_full (нет свободных мест), double_booking (повторная бронь того же слота), slot_cancelled (слот отменён клубом), slot_started (слот уже стартовал), already_cancelled (бронь уже отменена), invalid_code (неверный/истёкший OTP). Идемпотентность: idempotency_key_conflict (повтор ключа с другим телом). Транспортные/общие: bad_request (400), unauthorized (401), forbidden (403), not_found (404), too_many_requests (429), internal_error (5xx).
type ErrorCode string

// Instructor Маршал-инструктор, ведущий заезд (брифинг и контроль безопасности).
type Instructor struct {
	// Id Идентификатор маршала-инструктора.
	Id openapi_types.UUID `json:"id"`

	// Name Имя маршала-инструктора.
	Name string `json:"name"`
}

// InstructorListResponse Постраничный список маршалов-инструкторов (справочник для фильтра, BS-001).
type InstructorListResponse struct {
	// Items Элементы списка маршалов.
	Items []Instructor `json:"items"`

	// Meta Метаданные постраничной выдачи.
	Meta PaginationMeta `json:"meta"`
}

// PaginationMeta Метаданные постраничной выдачи.
type PaginationMeta struct {
	// Limit Размер страницы.
	Limit int `json:"limit"`

	// Offset Смещение от начала выборки.
	Offset int `json:"offset"`

	// Total Общее число элементов.
	Total int `json:"total"`
}

// LimitParam defines model for LimitParam.
type LimitParam = int

// OffsetParam defines model for OffsetParam.
type OffsetParam = int

// InternalError Стандартное тело ошибки.
type InternalError = Error

// Unauthorized Стандартное тело ошибки.
type Unauthorized = Error

// ListInstructorsParams defines parameters for ListInstructors.
type ListInstructorsParams struct {
	// Limit Максимальное число элементов в выдаче
	Limit *LimitParam `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Смещение от начала выдачи
	Offset *OffsetParam `form:"offset,omitempty" json:"offset,omitempty"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Справочник инструкторов
	// (GET /instructors)
	ListInstructors(w http.ResponseWriter, r *http.Request, params ListInstructorsParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Справочник инструкторов
// (GET /instructors)
func (_ Unimplemented) ListInstructors(w http.ResponseWriter, r *http.Request, params ListInstructorsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListInstructors operation middleware
func (siw *ServerInterfaceWrapper) ListInstructors(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListInstructorsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListInstructors(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/instructors", wrapper.ListInstructors)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/6xYW28bxxX+K4NpH0RgeZHsFijfEsAFHCS1YLvIgysQI3Iob7zcpXeHgllDAC/1DXKq",
	"uMhDEaRJkxc/FAUommtRvAnwLzjzF/pLinNml9wlV5ZzARJDO5yZc/++c+Yxr3qNpudKVwW8/Jg3hS8a",
	"Ukmfvj61G7baxSX8qsmg6ttNZXsuL3P4FgYw0V0YwwwGMNUvYQ4LCJl+BmPdhSksmP4SphDCDEKY6x4s",
	"YMjoP30MIxjoZxByi9t428OW9Nvc4q5oSF7mDgrmFg+q92VDGOF10XIUL++ULN4Qj+xGq8HL2yX8st3o",
	"y+Kq3cTztqvkgfT50ZHFb9XrgbzUih9QO/0CNYQxhAwWusdgTtoNYAqDpLrjS9T1SES2vkkFSxkKHlnc",
	"l0HTcwNJPr/pKum7wrnh+56PC1XPVdJV+KdoNh27KlD34hcBGvCYy0ei0XSk2VmL78YbKpKusHhDBoE4",
	"wJ/gNYYhj/8wuICFfk5xgjnGrYcBLTD4HhZwoTuwgFPdh3PdQ7eE+oV+xXQHBnBGR+EM3kJY4EdJq3/r",
	"yzov898UV1lVNL8GRWMQGbwWg3/AXPd1T3coCnN9ok8Y6TaGU5jAgOkuhLoDQ0qsAcn8syta6r7n23+V",
	"tZ/lpVbygpSPfiRF0PZQ93QXlRnAEH2mOzCGMxjopzDWJ+SqkDaPYBA7agQhnOuu7pG6PQhNaehjOGdU",
	"AxO0kurgDAbwBhYYAhjiOvsoUomU/1V8+x2Z0Kd/ezA0RjEYwxTGFHcYRjbMU+plWAzjAhVUJBR1Wibp",
	"elVRMs2pbDq6FyMDeQPzbRXccYFbvOl7Tekr21SACdDGnd/QjQusU0QO3cXTcM4Qfui6eeRlmMACRikh",
	"bOt2vrRzLVdg8DUsDCDR7jDarY/LLHA8Vam3HIdtoWN0D/NuiGWAO3C7fsIILrq6l7NYzWvtO7Ky73kP",
	"bPeAbVFVxF5DBDlhcEp1NNcvjXPfoPFv0RUEkOilnGUEV4VblY4ja2wr/pHAKELPVxiUCUx1n9SZxccC",
	"JXyVOqT7kQS8nbyP2TWAac5iwvGlqLWTwpIqmpMrqfQ/ami7h8KxaxUMjfFOlDbk8SLWpe7pVzAhl5+z",
	"W3d30df/pGqYEdL0IhKYw4I2vywzuyYbTU9Jt9quPJDtStVz645dVWlXGrP/jnjMdJfBSHd0H94g7ywz",
	"CmYo7keCp7nukkDKOwxxkZDsBcJ7me2LWsWXD1syUGzreqmUs1gSCXBtO2exuufv27WadHHhWs5iLuaG",
	"13Jpx/WcxZTnVRrCbce3BWzr+s4fyFdJ+GVbv3v0KIdJLl2kgHt8mWbc4ukUQgJJpUK8EAWZW3wjgMRI",
	"q+Dg5yVe5RZPGM+tdQRcmoy8FlvLLb5hKIlMUcyetQLYlH0R2wXKR/MInZSwnSCjvP8FIcXphOAmiZth",
	"ssQX1F4guoQwMz+OsFaJrMf4McW6G9HmAcySYKGfYN0tonQwjH9OZE85hglCKRqyLTKeUDhg717/Plem",
	"bUSLY4KAjsWo/+np/rL7GRjJJr/7cLHK9VivG9vFGzsW08+oKk/1saHSCbIqWq1fsnf/gR+SqAOLMvvT",
	"EnbeTVkxc8tnBsiw1rDlmkTtlv6SUPICxlTlyDLjd1MGpxDCWUTneA3+ZappYoCDRYS4Cc/iUNiOwLT1",
	"pauEUzmQIpMDSCH0zIS6DVJgQrGNoPRDFWbET8secw2WYcG24rAjbD9BtNM9OvhLpJqijdM6o7e0Eq4I",
	"pFDB1U6IonilQSYnZzFVGSpIsFlk74qxisbUEJtV/dzkNjokZquULTuZfXK05O1/IasKrVu2RBtWvY5Q",
	"d4guTJekIfr1KkNSgdOkEWFKI55O6BTTMlqd6pdolwlxr7CJLdRHP2zZPvaD93gEhrENexn23XQD5beq",
	"KrOD+Za48zkGKY9YQnWMxDMxrGQxsn6k+8Qs56abC+EMRhGnjvXfCITeMEzECXFsj9JrioBAFYidNgx0",
	"N0aKKOvSBWfXMvQz1IpoZeSYFCe6nK1Uh0Gm8thDE+A3hMJWuGXXssDaTDcZomcmtT5MTCLIX0VF18Ue",
	"+coQklKkw/uj96kdqNvRCJWh7vcRCFNvQHQQNeNdqndM1UnamgUMs+1BqMBG64IuG1LmY3pPYnynUGCq",
	"kjiLfXwnXyptZ8VUyUYWXvw3OTDr45WSEwMIKSXx2uVF7xsPEpm+KnTh+6Jt6lxdOWDsigPbJT78DHdv",
	"hIq0iK7Kitba+ax6MyQ+oihFtH+xGTpYYK0lRvJN35rHg00R/yayI/JmqWuf6uM0PpaywD4a8n/2E4Jh",
	"2WjiWcrKFKU8JZwMSd9FkHrFI0tKwPVstE9GL35tWT5jGPmbccThT1Zbvq3adzAxjL/3pfClj6Pr6uuP",
	"MbZ88vldvj6UfvL5XSaqVRkE+dXIaa2i+ioeuyn+aB3bvXXnLitiv1o8lL5db+dpFEFkRdaYExlN9cly",
	"ZKeur0NdTuKsL+u+DO6nJ/eVvKtn8jL7mOxjf2mVSteqxoqK8h5Il1aoX6KiQb8ZX6yA7r5STTOl227d",
	"y0ylDGi5FIlwFMh7rtPOZeMPOTDzvO4XGLxG5jHdaaL7Jawxk+pHuzfXnl6MfwwijaMuJXuFmBD72yEj",
	"bsJpjNgwr59GgjoQYiv7FVwYUng3JVq3lSGLby45tXaGtPxf52u2AjlEokPpB8ap24VSoUQF3JSuaNq8",
	"zK8VSoVriBtC3acULtqJw+XH/OCSQk8QxmVR+cmRYFsxS7DbcUBZFsmgdxDnKBFv1niZI/OlzU6+397L",
	"hvTVlmLifffIunJ38iH1aG/t2XKnVPqAZ7gPe826hNqznrc+JCQY++ul7cukLs0opt4USVb0hnvVwfSb",
	"LcFkq9EQfvun1jTmvzjA2PFkXPeOktBLkU2C7r09DEcg/cM47mkv7fperVXFDyqUaCga0fxKs0Ie/Ue6",
	"vI1ZjFu85TsRZgXlYlE07YJoykf5B8JXtntQiBimeLhNyZMWeUch4R+QPBwrqbldUI9Ps8BV0gJzPv9e",
	"qXtLb/0iIF294yd9frR39P8AAAD//+3oErodGQAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
