// Package bookingsapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package bookingsapi

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for BookingStatus.
const (
	BookingStatusActive        BookingStatus = "active"
	BookingStatusCancelled     BookingStatus = "cancelled"
	BookingStatusClubCancelled BookingStatus = "club_cancelled"
	BookingStatusLateCancel    BookingStatus = "late_cancel"
)

// Defines values for ErrorCode.
const (
	ErrorCodeAlreadyCancelled       ErrorCode = "already_cancelled"
	ErrorCodeBadRequest             ErrorCode = "bad_request"
	ErrorCodeDoubleBooking          ErrorCode = "double_booking"
	ErrorCodeForbidden              ErrorCode = "forbidden"
	ErrorCodeIdempotencyKeyConflict ErrorCode = "idempotency_key_conflict"
	ErrorCodeInternalError          ErrorCode = "internal_error"
	ErrorCodeInvalidCode            ErrorCode = "invalid_code"
	ErrorCodeNotFound               ErrorCode = "not_found"
	ErrorCodeSlotCancelled          ErrorCode = "slot_cancelled"
	ErrorCodeSlotFull               ErrorCode = "slot_full"
	ErrorCodeSlotStarted            ErrorCode = "slot_started"
	ErrorCodeTooManyRequests        ErrorCode = "too_many_requests"
	ErrorCodeUnauthorized           ErrorCode = "unauthorized"
)

// Defines values for RouteType.
const (
	Experienced RouteType = "experienced"
	Novice      RouteType = "novice"
)

// Defines values for SlotStatus.
const (
	SlotStatusCancelled SlotStatus = "cancelled"
	SlotStatusScheduled SlotStatus = "scheduled"
)

// Defines values for ListBookingsParamsStatus.
const (
	Active        ListBookingsParamsStatus = "active"
	Cancelled     ListBookingsParamsStatus = "cancelled"
	ClubCancelled ListBookingsParamsStatus = "club_cancelled"
	LateCancel    ListBookingsParamsStatus = "late_cancel"
)

// Booking Полные данные брони для экрана деталей (SCR-006). Тарифы (price за место, rental_price за прокатную экипировку) и валюта лежат в booking.slot, а не на верхнем уровне брони (R-005); на уровне брони присутствует только производное итоговое поле price_total.
type Booking struct {
	// CancellationReason Причина отмены брони. Заполняется при club_cancelled (текст причины от клуба, например «отмена по погоде»); для cancelled/late_cancel и active — null (R-008, R-025).
	CancellationReason *string `json:"cancellation_reason"`

	// CancelledAt Дата и время отмены, если бронь была отменена.
	CancelledAt *time.Time `json:"cancelled_at"`

	// ClientId Идентификатор клиента, оформившего бронь.
	ClientId openapi_types.UUID `json:"client_id"`

	// CreatedAt Дата и время создания брони.
	CreatedAt time.Time `json:"created_at"`

	// Id Идентификатор брони.
	Id openapi_types.UUID `json:"id"`

	// PriceTotal Производное поле только для чтения, в рублях (валюта RUB) = slot.price·seats_count + slot.rental_price·rental_count (R-005). Сами тарифы price/rental_price берутся из booking.slot.
	PriceTotal *int `json:"price_total,omitempty"`

	// RentalCount Число прокатных комплектов экипировки (0..seats_count).
	RentalCount int `json:"rental_count"`

	// SeatsCount Число забронированных мест.
	SeatsCount int `json:"seats_count"`

	// Slot Полная карточка слота (конкретный заезд на дату/время). Доступен только для чтения. Статус «Прошедшая» — производное значение по полю start_at, отдельным статусом не хранится.
	//
	// Доступность (R-013): максимально доступное к брони число мест max_seats = min(free_seats, route.capacity_cap, 5). Число прокатных комплектов экипировки в брони ограничено: rental_count ≤ free_rental_gear. Клиент со своей экипировкой занимает место (free_seats), но не расходует прокатный фонд (free_rental_gear).
	//
	// Цены (R-010): price — тариф за место, rental_price — отдельный тариф проката за экипировку, оба в рублях (валюта RUB). Итоговая цена брони производная = price·seats_count + rental_price·rental_count.
	//
	// Инварианты: free_seats ≤ total_seats; счётчики (free_seats, free_rental_gear, total_seats) и цены (price, rental_price) неотрицательны.
	Slot *Slot `json:"slot,omitempty"`

	// SlotId Идентификатор слота, на который оформлена бронь.
	SlotId openapi_types.UUID `json:"slot_id"`

	// Status Статус брони. late_cancel — поздняя отмена (менее 1 часа до начала): место и экипировка НЕ освобождаются. club_cancelled — «Отменена клубом»: слот снят клубом (Slot.status = cancelled), бронь отменена не по инициативе клиента, места и экипировки освобождаются (R-008).
	Status BookingStatus `json:"status"`
}

// BookingListResponse Постраничный список броней (SCR-005).
type BookingListResponse struct {
	// Items Элементы списка броней.
	Items []BookingSummary `json:"items"`

	// Meta Метаданные постраничной выдачи.
	Meta PaginationMeta `json:"meta"`
}

// BookingStatus Статус брони. late_cancel — поздняя отмена (менее 1 часа до начала): место и экипировка НЕ освобождаются. club_cancelled — «Отменена клубом»: слот снят клубом (Slot.status = cancelled), бронь отменена не по инициативе клиента, места и экипировки освобождаются (R-008).
type BookingStatus string

// BookingSummary Урезанное представление брони для списка (SCR-005).
type BookingSummary struct {
	// CancellationReason Причина отмены брони. Заполняется при club_cancelled (текст причины от клуба, например «отмена по погоде»); для cancelled/late_cancel и active — null (R-008, R-025).
	CancellationReason *string `json:"cancellation_reason"`

	// CancelledAt Дата и время отмены, если бронь была отменена.
	CancelledAt *time.Time `json:"cancelled_at"`

	// CreatedAt Дата и время создания брони.
	CreatedAt time.Time `json:"created_at"`

	// Id Идентификатор брони.
	Id openapi_types.UUID `json:"id"`

	// PriceTotal Производное поле только для чтения, в рублях (валюта RUB) = slot.price·seats_count + slot.rental_price·rental_count (R-005). Сами тарифы price/rental_price берутся из booking.slot.
	PriceTotal *int `json:"price_total,omitempty"`

	// RentalCount Число прокатных комплектов экипировки (0..seats_count).
	RentalCount int `json:"rental_count"`

	// SeatsCount Число забронированных мест.
	SeatsCount int `json:"seats_count"`

	// Slot Урезанное представление слота для списка (SCR-002).
	Slot *SlotSummary `json:"slot,omitempty"`

	// SlotId Идентификатор слота, на который оформлена бронь.
	SlotId openapi_types.UUID `json:"slot_id"`

	// Status Статус брони. late_cancel — поздняя отмена (менее 1 часа до начала): место и экипировка НЕ освобождаются. club_cancelled — «Отменена клубом»: слот снят клубом (Slot.status = cancelled), бронь отменена не по инициативе клиента, места и экипировки освобождаются (R-008).
	Status BookingStatus `json:"status"`
}

// CreateBookingRequest Запрос на создание брони.
type CreateBookingRequest struct {
	// RentalCount Число прокатных комплектов экипировки. Не больше seats_count.
	RentalCount int `json:"rental_count"`

	// SeatsCount Число мест.
	SeatsCount int `json:"seats_count"`

	// SlotId Идентификатор слота.
	SlotId openapi_types.UUID `json:"slot_id"`
}

// CreateBookingResponse defines model for CreateBookingResponse.
type CreateBookingResponse struct {
	// CancellationReason Причина отмены брони. Заполняется при club_cancelled (текст причины от клуба, например «отмена по погоде»); для cancelled/late_cancel и active — null (R-008, R-025).
	CancellationReason *string `json:"cancellation_reason"`

	// CancelledAt Дата и время отмены, если бронь была отменена.
	CancelledAt *time.Time `json:"cancelled_at"`

	// ClientId Идентификатор клиента, оформившего бронь.
	ClientId openapi_types.UUID `json:"client_id"`

	// CreatedAt Дата и время создания брони.
	CreatedAt time.Time `json:"created_at"`

	// Id Идентификатор брони.
	Id openapi_types.UUID `json:"id"`

	// IsFirstBooking true, если это первая успешная бронь клиента (для приветственного сценария/онбординга на клиенте), R-006.
	IsFirstBooking bool `json:"is_first_booking"`

	// PriceTotal Производное поле только для чтения, в рублях (валюта RUB) = slot.price·seats_count + slot.rental_price·rental_count (R-005). Сами тарифы price/rental_price берутся из booking.slot.
	PriceTotal *int `json:"price_total,omitempty"`

	// ReminderHours За сколько часов до старта слота клиенту будут отправлены напоминания (push). Используется клиентом для информирования пользователя; пусто/отсутствует — напоминания не настроены (R-006). Канонический MVP-набор — `[24, 2]` (за 24 ч и за 2 ч до старта, согласовано с заказчиком 2026-06-25); значение задаётся сервером, клиент его не хардкодит.
	ReminderHours *[]int `json:"reminder_hours,omitempty"`

	// RentalCount Число прокатных комплектов экипировки (0..seats_count).
	RentalCount int `json:"rental_count"`

	// SeatsCount Число забронированных мест.
	SeatsCount int `json:"seats_count"`

	// Slot Полная карточка слота (конкретный заезд на дату/время). Доступен только для чтения. Статус «Прошедшая» — производное значение по полю start_at, отдельным статусом не хранится.
	//
	// Доступность (R-013): максимально доступное к брони число мест max_seats = min(free_seats, route.capacity_cap, 5). Число прокатных комплектов экипировки в брони ограничено: rental_count ≤ free_rental_gear. Клиент со своей экипировкой занимает место (free_seats), но не расходует прокатный фонд (free_rental_gear).
	//
	// Цены (R-010): price — тариф за место, rental_price — отдельный тариф проката за экипировку, оба в рублях (валюта RUB). Итоговая цена брони производная = price·seats_count + rental_price·rental_count.
	//
	// Инварианты: free_seats ≤ total_seats; счётчики (free_seats, free_rental_gear, total_seats) и цены (price, rental_price) неотрицательны.
	Slot *Slot `json:"slot,omitempty"`

	// SlotId Идентификатор слота, на который оформлена бронь.
	SlotId openapi_types.UUID `json:"slot_id"`

	// Status Статус брони. late_cancel — поздняя отмена (менее 1 часа до начала): место и экипировка НЕ освобождаются. club_cancelled — «Отменена клубом»: слот снят клубом (Slot.status = cancelled), бронь отменена не по инициативе клиента, места и экипировки освобождаются (R-008).
	Status BookingStatus `json:"status"`
}

// Error Стандартное тело ошибки.
type Error struct {
	// Code Канонический машинный код ошибки (R-023). Доменные коды: slot_full (нет свободных мест), double_booking (повторная бронь того же слота), slot_cancelled (слот отменён клубом), slot_started (слот уже стартовал), already_cancelled (бронь уже отменена), invalid_code (неверный/истёкший OTP). Идемпотентность: idempotency_key_conflict (повтор ключа с другим телом). Транспортные/общие: bad_request (400), unauthorized (401), forbidden (403), not_found (404), too_many_requests (429), internal_error (5xx).
	Code ErrorCode `json:"code"`

	// Details Необязательные машиночитаемые детали для динамических сообщений на клиенте (foundations §6): например, актуальная доступность для E1/E2, чтобы показать «Свободно: N мест» / «Свободно: M комплектов экипировки» без разбора текста message.
	Details *struct {
		// AvailableRentalGear Сколько прокатных комплектов экипировки реально свободно (для нехватки прокатных комплектов экипировки).
		AvailableRentalGear *int `json:"available_rental_gear,omitempty"`

		// AvailableSeats Сколько мест реально свободно на момент ошибки (для slot_full / превышения мест).
		AvailableSeats *int `json:"available_seats,omitempty"`
	} `json:"details,omitempty"`

	// Message Человекочитаемое сообщение об ошибке.
	Message string `json:"message"`
}

// ErrorCode Канонический машинный код ошибки (R-023). Доменные коды: slot_full (нет свободных мест), double_booking (повторная бронь того же слота), slot_cancelled (слот отменён клубом), slot_started (слот уже стартовал), already_cancelled (бронь уже отменена), invalid_code (неверный/истёкший OTP). Идемпотентность: idempotency_key_conflict (повтор ключа с другим телом). Транспортные/общие: bad_request (400), unauthorized (401), forbidden (403), not_found (404), too_many_requests (429), internal_error (5xx).
type ErrorCode string

// Geometry Геометрия трассы для отрисовки линии на карте Яндекс.
type Geometry struct {
	union json.RawMessage
}

// Geometry0 Массив координат точек трассы.
type Geometry0 = [][]float32

// Geometry1 Закодированная полилиния (encoded polyline).
type Geometry1 = string

// Instructor Маршал-инструктор, ведущий заезд (брифинг и контроль безопасности).
type Instructor struct {
	// Id Идентификатор маршала-инструктора.
	Id openapi_types.UUID `json:"id"`

	// Name Имя маршала-инструктора.
	Name string `json:"name"`
}

// PaginationMeta Метаданные постраничной выдачи.
type PaginationMeta struct {
	// Limit Размер страницы.
	Limit int `json:"limit"`

	// Offset Смещение от начала выборки.
	Offset int `json:"offset"`

	// Total Общее число элементов.
	Total int `json:"total"`
}

// Route Конфигурация трассы заезда (короткая новичковая / длинная опытная). Справочник, доступен только для чтения.
type Route struct {
	// CapacityCap Потолок числа мест на трассе. Новичковая — не более 8, опытная — не более 14.
	CapacityCap int `json:"capacity_cap"`

	// Description Описательный текст конфигурации / заезда для карточки слота (SCR-003). Опционально; может отсутствовать или быть null.
	Description *string `json:"description"`

	// DurationMin Продолжительность заезда в минутах (обычно 15–20, включая инструктаж).
	DurationMin int `json:"duration_min"`

	// Geometry Геометрия трассы для отрисовки линии на карте Яндекс.
	Geometry Geometry `json:"geometry"`

	// Id Идентификатор конфигурации трассы.
	Id openapi_types.UUID `json:"id"`

	// Name Название конфигурации трассы.
	Name string `json:"name"`

	// Type Тип конфигурации трассы — новичковая (novice) или опытная (experienced).
	Type RouteType `json:"type"`
}

// RouteType Тип конфигурации трассы — новичковая (novice) или опытная (experienced).
type RouteType string

// Slot Полная карточка слота (конкретный заезд на дату/время). Доступен только для чтения. Статус «Прошедшая» — производное значение по полю start_at, отдельным статусом не хранится.
//
// Доступность (R-013): максимально доступное к брони число мест max_seats = min(free_seats, route.capacity_cap, 5). Число прокатных комплектов экипировки в брони ограничено: rental_count ≤ free_rental_gear. Клиент со своей экипировкой занимает место (free_seats), но не расходует прокатный фонд (free_rental_gear).
//
// Цены (R-010): price — тариф за место, rental_price — отдельный тариф проката за экипировку, оба в рублях (валюта RUB). Итоговая цена брони производная = price·seats_count + rental_price·rental_count.
//
// Инварианты: free_seats ≤ total_seats; счётчики (free_seats, free_rental_gear, total_seats) и цены (price, rental_price) неотрицательны.
type Slot struct {
	// FreeRentalGear Число свободных прокатных комплектов экипировки из общего фонда (расчётное). Ограничивает rental_count в брони (rental_count ≤ free_rental_gear). Своя экипировка фонд не расходует, R-013.
	FreeRentalGear int `json:"free_rental_gear"`

	// FreeSeats Число свободных мест (расчётное). Своя экипировка клиента тоже занимает место. К брони доступно max_seats = min(free_seats, route.capacity_cap, 5), R-013.
	FreeSeats int `json:"free_seats"`

	// Id Идентификатор слота.
	Id openapi_types.UUID `json:"id"`

	// Instructor Маршал-инструктор, ведущий заезд (брифинг и контроль безопасности).
	Instructor Instructor `json:"instructor"`

	// MeetingPoint Адрес или ориентир места встречи.
	MeetingPoint string `json:"meeting_point"`

	// MeetingPointLat Широта места встречи.
	MeetingPointLat float32 `json:"meeting_point_lat"`

	// MeetingPointLng Долгота места встречи.
	MeetingPointLng float32 `json:"meeting_point_lng"`

	// Price Цена за одно место, в рублях (целое число, валюта RUB).
	Price int `json:"price"`

	// RentalPrice Тариф проката за одну экипировку, в рублях (целое число, валюта RUB).
	RentalPrice int `json:"rental_price"`

	// Route Конфигурация трассы заезда (короткая новичковая / длинная опытная). Справочник, доступен только для чтения.
	Route Route `json:"route"`

	// StartAt Дата и время начала заезда.
	StartAt time.Time `json:"start_at"`

	// Status Статус слота.
	Status SlotStatus `json:"status"`

	// TotalSeats Общее число мест в слоте.
	TotalSeats int `json:"total_seats"`
}

// SlotStatus Статус слота.
type SlotStatus string

// SlotSummary Урезанное представление слота для списка (SCR-002).
type SlotSummary struct {
	// FreeRentalGear Число свободных прокатных комплектов экипировки из общего фонда (расчётное). Ограничивает rental_count в брони (rental_count ≤ free_rental_gear). Своя экипировка фонд не расходует, R-013.
	FreeRentalGear int `json:"free_rental_gear"`

	// FreeSeats Число свободных мест (расчётное). Своя экипировка клиента тоже занимает место. К брони доступно max_seats = min(free_seats, route.capacity_cap, 5), R-013.
	FreeSeats int `json:"free_seats"`

	// Id Идентификатор слота.
	Id openapi_types.UUID `json:"id"`

	// Instructor Маршал-инструктор, ведущий заезд (брифинг и контроль безопасности).
	Instructor Instructor `json:"instructor"`

	// Price Цена за одно место, в рублях (целое число, валюта RUB).
	Price int `json:"price"`

	// RentalPrice Тариф проката за одну экипировку, в рублях (целое число, валюта RUB).
	RentalPrice int `json:"rental_price"`

	// Route Конфигурация трассы заезда (короткая новичковая / длинная опытная). Справочник, доступен только для чтения.
	Route Route `json:"route"`

	// StartAt Дата и время начала заезда.
	StartAt time.Time `json:"start_at"`

	// Status Статус слота.
	Status SlotStatus `json:"status"`

	// TotalSeats Общее число мест в слоте.
	TotalSeats int `json:"total_seats"`
}

// BookingIdParam defines model for BookingIdParam.
type BookingIdParam = openapi_types.UUID

// BookingStatusParam defines model for BookingStatusParam.
type BookingStatusParam = []string

// LimitParam defines model for LimitParam.
type LimitParam = int

// OffsetParam defines model for OffsetParam.
type OffsetParam = int

// BadRequest Стандартное тело ошибки.
type BadRequest = Error

// Conflict Стандартное тело ошибки.
type Conflict = Error

// Forbidden Стандартное тело ошибки.
type Forbidden = Error

// Gone Стандартное тело ошибки.
type Gone = Error

// InternalError Стандартное тело ошибки.
type InternalError = Error

// NotFound Стандартное тело ошибки.
type NotFound = Error

// Unauthorized Стандартное тело ошибки.
type Unauthorized = Error

// UnprocessableEntity Стандартное тело ошибки.
type UnprocessableEntity = Error

// ListBookingsParams defines parameters for ListBookings.
type ListBookingsParams struct {
	// Status Фильтр броней по статусу (множественный выбор, OR внутри группы), R-025. Без параметра возвращаются брони всех статусов, включая cancelled и late_cancel.
	Status *BookingStatusParam `form:"status,omitempty" json:"status,omitempty"`

	// Limit Максимальное число элементов в выдаче
	Limit *LimitParam `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Смещение от начала выдачи
	Offset *OffsetParam `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListBookingsParamsStatus defines parameters for ListBookings.
type ListBookingsParamsStatus string

// CreateBookingParams defines parameters for CreateBooking.
type CreateBookingParams struct {
	// IdempotencyKey Обязательный ключ идемпотентности (UUID) для безопасного повтора при сетевом сбое (NFR-9, R-022). Хранится ≥24 ч; повтор с тем же ключом и телом → тот же ответ, с другим телом → 409.
	IdempotencyKey openapi_types.UUID `json:"Idempotency-Key"`
}

// CreateBookingJSONRequestBody defines body for CreateBooking for application/json ContentType.
type CreateBookingJSONRequestBody = CreateBookingRequest

// AsGeometry0 returns the union data inside the Geometry as a Geometry0
func (t Geometry) AsGeometry0() (Geometry0, error) {
	var body Geometry0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromGeometry0 overwrites any union data inside the Geometry as the provided Geometry0
func (t *Geometry) FromGeometry0(v Geometry0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeGeometry0 performs a merge with any union data inside the Geometry, using the provided Geometry0
func (t *Geometry) MergeGeometry0(v Geometry0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsGeometry1 returns the union data inside the Geometry as a Geometry1
func (t Geometry) AsGeometry1() (Geometry1, error) {
	var body Geometry1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromGeometry1 overwrites any union data inside the Geometry as the provided Geometry1
func (t *Geometry) FromGeometry1(v Geometry1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeGeometry1 performs a merge with any union data inside the Geometry, using the provided Geometry1
func (t *Geometry) MergeGeometry1(v Geometry1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Geometry) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Geometry) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Мои брони
	// (GET /bookings)
	ListBookings(w http.ResponseWriter, r *http.Request, params ListBookingsParams)
	// Создать бронь
	// (POST /bookings)
	CreateBooking(w http.ResponseWriter, r *http.Request, params CreateBookingParams)
	// Детали брони
	// (GET /bookings/{bookingId})
	GetBooking(w http.ResponseWriter, r *http.Request, bookingId BookingIdParam)
	// Отменить бронь
	// (POST /bookings/{bookingId}/cancel)
	CancelBooking(w http.ResponseWriter, r *http.Request, bookingId BookingIdParam)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Мои брони
// (GET /bookings)
func (_ Unimplemented) ListBookings(w http.ResponseWriter, r *http.Request, params ListBookingsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Создать бронь
// (POST /bookings)
func (_ Unimplemented) CreateBooking(w http.ResponseWriter, r *http.Request, params CreateBookingParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Детали брони
// (GET /bookings/{bookingId})
func (_ Unimplemented) GetBooking(w http.ResponseWriter, r *http.Request, bookingId BookingIdParam) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Отменить бронь
// (POST /bookings/{bookingId}/cancel)
func (_ Unimplemented) CancelBooking(w http.ResponseWriter, r *http.Request, bookingId BookingIdParam) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListBookings operation middleware
func (siw *ServerInterfaceWrapper) ListBookings(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListBookingsParams

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", r.URL.Query(), &params.Status)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListBookings(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateBooking operation middleware
func (siw *ServerInterfaceWrapper) CreateBooking(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateBookingParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey openapi_types.UUID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateBooking(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetBooking operation middleware
func (siw *ServerInterfaceWrapper) GetBooking(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "bookingId" -------------
	var bookingId BookingIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "bookingId", chi.URLParam(r, "bookingId"), &bookingId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "bookingId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetBooking(w, r, bookingId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CancelBooking operation middleware
func (siw *ServerInterfaceWrapper) CancelBooking(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "bookingId" -------------
	var bookingId BookingIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "bookingId", chi.URLParam(r, "bookingId"), &bookingId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "bookingId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CancelBooking(w, r, bookingId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/bookings", wrapper.ListBookings)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/bookings", wrapper.CreateBooking)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/bookings/{bookingId}", wrapper.GetBooking)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/bookings/{bookingId}/cancel", wrapper.CancelBooking)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x9bW8b15X/V7mY//8FiR2RlGynCY28aLpJ4W5bG3ayfeEK6pgcydOQQ3Y4NKw1BIhk",
	"HDuQG9WtF1sUbbru9mGBYLGUrLEoiqQAfYI7XyGfZHHOuXfm3nkQKUVNd1EDbZIZzsy999zzfH7n6pFR",
	"azXbLdd2/Y5RfWS0Lc9q2r7t4dV7rdbHjrtxo34LbsOdut2peU7bd1quUTX4r/kBD/g07PNR+Akf8TEf",
	"hn0+C7cZ3wu3+YxP+Qj/vc+H+N+7hmk48Grb8u8bpuFaTduoGvfkQIZpePbPuo5n142q73Vt0+jU7ttN",
	"CwZfb3lNyzeqRrfrwJP+Zhte7vie424YW1umnPAd3/K7nbxJ/5GP+HH4LOyr0wz4EeMnfMbCXtiHVYSD",
	"sBcOWIFP+JTP+Gse4C/7sF4+DXfg+f1wh+/Bck128zbj+3waDuCzfMT4q3A7HPATfhLuFE12e6mycq3E",
	"+HMe8EMYaBhu8yGf8ACfH8LLM37I9+Ei/IwPw8/DftgLdxVCwng9HoSPtTkCcU14fcyPw8/DJ3wY7rKa",
	"5dbsRsOuMz5iDcu31+hOyTAN+2G70arbkry4Gz/r2t5mvB0dpJ+h0t7x7SbyhO12m0b1rmHVfOeBbZhG",
	"NJZhGspQ8Euje28t/nk1tWPRDcvzrE247vibDbgBWw3X33eajp+3kb/lQz4Oe3zEJ3wIW4o7FbDwCR+F",
	"PX4Mu/lzfswDoDNy6YzvM/xfuMMP+DB8wgMjmwQNGFijQN1et7oN36iuVEyjaT10mkCI5QpcOa64ilbk",
	"uL69YXvIlTfX1zt27ipeIhd8hnw14gHjs7DP+BRnN+THyBvRdEc5023hENnzVSdYyZjgFshcp91yOzZJ",
	"vVW/bf+sa3d8uKq1XN928T+tdrvh1CyYePmnHZj9I8N+aDXbsGXwZB1l2aqveeJ902janY61Aff573gA",
	"4hNuo/gEKSkIdxg/5EN+Agwf9viwxPjvhfYIwm2QWHhrDAIXbvOAj8M+7DhIQ/gMPhfg7QPUNdNwJ3wM",
	"HyRKEnWPSshkEY3+v2evG1Xj/5VjLVimXzvl9z2vJciT2LFzL4QVYBZ4PcKHtk3WsS2/s1ZrdV0fNQd8",
	"54CP4DE+5Ico8kO2XCpdY6Cv+Ih5tutbDfnKHp+hFnvKA/VbRVzhd1ruesOpXWwDO42Wv7bebYAI123f",
	"chrIFtYDy2lY9xr2mpjIhm15yPLxLzgRo1rZSmy84OE9pNIUxXTCSERpU6fE+KjX8G4vfAYPgFaElR7I",
	"/ZyQHr6kfRyCkgYSStkb8SnYKtyoIaqMIftq+wVOMOyfNSO5S7TrwhKKR8awXn6Cqmgs1FD4cz7mI34S",
	"GcgxH7GCZHa+Fw7w9yl/ZbJoR4omMAlM4Qj5OjYP4TNWqLe6sAnCmMKzJ/A9ssjyeSA4qkNgS6vh2VZ9",
	"M1bSRQaLgAVqL7MbdbvZbvm2W9tc+id7k4U9xg/Qwr0Clmawi7BvfJJifSd+de1je3OtJniTjOIKMewH",
	"Le+eU6/b7oU4dj16W+O7F0I3DPhJPKsg/Cx8zqclxn8JcoqMNxEGHllxRmyKRrgfPiMjPGaxWoE1yrXP",
	"4P+wwUA1sjHDS+HN3/MZuA5hHzgJBo+WApdjFj4JB/w10l6dGY793ZZrX1zyVXuuEPMlCavCQEBG8C9I",
	"FfFAyLE21wAeOeDHmiOje4SXQq6c2RXIk3k35m8c7Ybr255rNeh7F6GUI76wZuMnNEr9BWRmCf6BMhQ+",
	"RU8EOQ3V2xjsGm7vNjLbgB8R5yFrMtSRhyR+h8CWl0KgX0a+Kfmvu6QLnqKwA4uha7nN99F1Ih7+Ycv/",
	"oNV16xeikAsqC9/WiPNvQgyHODQwQcAn6E2jbPbCQbgNymVK3DTkRxRiXAoRvtbgH7lW17/f8px/sS9G",
	"ka76AY0of8BtAU4IpNc/jPT2CFRX+CmKCjBO7OQItoEpHongZESKGFxhWlcfbRGK4T4pwVcorWRxAvZt",
	"MSWc/KUQ+QtcwgD/2ef7tKjIOk4j3wnmpE4vY8V8JCjf9lo1INe9hv2+6zv+5sXVW8e3PD9PuaFODWR8",
	"tU2mGjwSE+wCOZhiL9K6bnpJqv+LrIEoPCRDBaYbY1W+h7QC36S3RJwNPMCPw4H0WhJep/S58ldawpBF",
	"zFJJAmRELr9HThI+cGyEAi1mJeUP3o5w/tCaBcLRg7C7cOc7t5cqlbeKJcb/QL5X+Em4wwptz6nZyLSR",
	"l8VnpvSD1V91n2sQfp7hXoWDIlorXCWE1/AizOA1vAbiIRynEvCJyeBnqQiYCEEe415MGCgK/OpUX20B",
	"FnKteJ1eynuKtiRDSHAXQHjHaDvwBdjgffI3MbhFEUe3A28HZCiOecCQIGt+y7cwzm97rbbt+Q4FdcIC",
	"ooisebYlhCS5ozixJ+h3DlVjuqPMv8RIkYrd342VFq6L6WE/K6BKGpOPfBIPAN9Ekz0GfuV7fGimGJad",
	"fqk5rMT1J2L9Bzw4PQZiE49FQ5aVNARsOaUqUCLcbqNBu/S2SMoUKScidAWqr/zhIODuNjDWkfkTcKBv",
	"uo1NeZ1KcUTTWrP8DJK/QKYdEmuiWpxobnq4Y4Jn0CP1GXv7fC/coexATKCAdJAZZ8rqlm8v+U7Tzph5",
	"eqYNx3b9Nad+vkyf5vyCogw/QTU+ARuLwRX6yNHUtQlmp/JMo+bZln8+mmEu7FAoopHmcebSJDXueRef",
	"PUTeqhQRzZG+DIGX8q1rB6FXn6B04XpN0GEYl+zBb+FjVtCU3e2P3iuydzGYLOFETg/VJMQ/0C+qdj09",
	"1HIOQruVGH+JyY4RI+Mh9DW+Uta18x6qzYFUECN+qGlZTfauvV2p5MpTlK6CJ+I5ZVDxL1Hy7+uF4pVS",
	"Sc+rKFNdVjKA185Or5mG8pWzpwveWVaQlEx9KBNZyZnIcuZEGi1/nltyB54Rz55XE0QJHaHJKVeHv1G+",
	"PNYMx1LDnk8riMT0nDVoVQCD8puypnDXwC/L5alKT9+pBJ+ZcVJcFWJNUcUJ7ta9n9o1pKOYy/edjn9b",
	"JFmzPSl0I7eF7noi3fceciUotrFeqxBOE5kv3dRHqfrEIP+lpsLDnfjjY2Uj4OPwyegjixC622xa3mZW",
	"Pr9p+3M94VvWhuOiY/IDeDq1XzgT8akzSHwn4o1kbiAulmhejOoloLd8IuxHFB0rmbLIwgZsmWGVpSfy",
	"MlquvlhVXFWwTxm6Zcj47/i/Yrozyia+xvy+qPmUki4UzO70S8U1CaR4kec045PT46ri3PdwDX3tCVYA",
	"2S4RG7N3Y3epaGp+xSw5ylQYIcqOjjAwA5GHCDpIm3+5/GHO8kdnrFy4ZqRsL7XQlGDVNJf8B/oRh1F+",
	"OiDzEfADkZXeF0prlB3gqMJ0hnC+8cPf+OFz/fA3vu8b3/eN7/s38X0VX+bvxgX+K7i938GfxSwUNEFO",
	"Qn5GWfdhQo9pljZtS78RYSiBtxbk1tu/AdG4FN6/OCMvwJUJ9lqIsxbgmjhcshqNm+tG9e5CTG9smY+S",
	"IVFnbd3xOr6sjadJgQo3NvDhz2X9jopiQ7A3A3TygvBpuvaue8GsIGue5EPtC9csgo+JunHYCz8lLYCG",
	"ZLeMnI6IMsSCTPkrcsCH+gABIcoqb2k8odmMe61Ww7ZcshlNx63b3tr9VtfrZEshQ881NrEiwkG81EGM",
	"itvG1cW8oU0rHDCsYR2AzSN3SJYkjqXzOhUO64RcW+GsFNrdzn2wrb9GCtM0DtVymLr6GdW8j8moTuNs",
	"o15XZvGX6LYoje1eh20ZUIhWhmlmZOLj6klqslFRQETsM7G2QlTE+A0+OxORfICkHfEj9oN/vrWEH8Id",
	"xjF+cnflqslWVn/CCljJWLnKwifo2+EVXiTpb5KWfAVeJ+0RjYegDLCjYz7kh+jco5JjK5WVt5Yqby2t",
	"YGVCR0QF9ArEYM8FsaNKcICrm5ga+ZnM52I9+zGy7gEOdMBHCS0Fi1tZVZIJad2kJwySdioptmmlsZpV",
	"fySBm2tRlC1bpJRVQMKOmVAzRWAw8C97UsyRsnwca40ZWHwlVNSVBFaC0sixHK4TDD9GhQO6+hWWl0Sd",
	"lIEELYUDVDAH+Pax9I1LRoaqjaAPWckSPkWG2CZ8HbnfARmjGDKQYZCpzpr6Zp488ImoxEeAWmQjbRDc",
	"o5UrsEcvcFlBvDX4dLhTjfFRCLSbA9QqmkwHSrFCFk4q1u2y3sZExVQqv6IAZqkhdi8HJaPkYeRrohCt",
	"vJRbky2aLIXUYgV1ivRmMgQtmsxxH1gNp74GW0PUUaCLR2UsQ/bD53yMJD9iNz+8hYoYHYMJ4lf6gmMj",
	"qGWV5WG6dFKyGJN8BmAMy76U+STtT3wHW1xGfMxnIDNVpuBKWeFqpVI0mYqogHvLRZNFWDC4caVosgiI",
	"AjeuFk3mt1prTcvdlF/rsMLVlXeQViqohxWuPXyoZaI0YKTGQtKdVlNUCbRBagMRyRtvDlzmUNUwE6Da",
	"BJJEhb+psJvUQnFIDbi0quZc1PWl4g4FCZoBh4V92kXYhoo/CVQRnyEsux+BbgIVBxDl0YTfgyF2rCwQ",
	"885ngh0EljfLMWIFXDym1zrs9C9vFasZKAjEjffDQYQaH9LIKpYjghXTvN5fLr+/YlLOAWaxQ+4FmloC",
	"CrLTL/lLVevwWZX9MFI7p8esnPnIDxaPRU6PMavADwVITLiKQxan9viQCVxLWj3nIHgzEOnjNA7hYpkE",
	"TFBF2PyEWuaz2FEGtf1YeGnjrwmjTeUr0m5HCrI8jwgS5TtvQcSTE2mqyBQo1kysN7ZYZZln3g93JBIZ",
	"CCKtVTLsy+gvSBn3CNmUEVYGAvwVYGZCEUky9EkpI0Csuoggkah9eQYkWg2ayTKX5kaPQhnKNWTFid+1",
	"W03bz0zj/wqVkeyrAUpSWS3shT0QWsFuM/FzLy5KHFN5g0BqqFfIBgeM/zc6RChhMP+Wa4toNN2QAuNA",
	"xEfcGgdyQwHvQcd7rE1KK7elXKfERxCLxBDldRC1HoQ77G7D8k3WcDdWtc8J0rnd5j1i/Kb18Ab9uIJp",
	"g/giWbpLXGfmbqTbr+TrSJdS3nYkiQoxnu3CztZZu9XYbDiuXcxghVUE53Z8r1vzM93T3+Jyn4IELmHw",
	"hzFYOCB9gLodPeBwgG7DEUU3AQQAwmGiRMeUv2Lkkc8wdN0mRhXqFbF+EFsJMyBUSiKncM5s+SSeOh9m",
	"Tn6hXIts+ckYekJ6Y7FhFAn+hdCoPR7wo7nyiZPCOWSJZqKYm7WDZPO1IOskXf+m4EnpfErvAPVopYf4",
	"d7SNVLjSPvspCVusTjMTc6KX6sKdWmSURYAUjZU5VF415Auhgef0smkDXM02DurWyaa2qFuMxs/ax9ut",
	"rm/nKKRU/JnSspHQYS4MO7YwkBiTdpiiuoBtHovUzC7YwQOhLmSnimiAwEuqvMh80gw5ZMTHJku1G8wr",
	"FWXVZNtWzfHBN2/ngDP6AjQ9jjdkqNg5TDREFOABJo3Ta5SdRGrLxNtmYqWZTy1f1fb67Sxm0qb9KAtV",
	"jND+NEI8qgrnJRfK+o7GuQgRpeIiR2peUFTAMW7/gp/gd7CjTXpO15WuG5ZMwsl8HSjkkSy47uC12200",
	"EurrN0n2GufwaOxraltTFdlOGm8ch94YtM74K0UtCdGn7jXJ12ghTE31SjP0HL0g3exEfYp6pD8pLVIb",
	"rnc9wg40HTe3jHqAfPNa7QaI4xltJ/cZ5ZmA9nyIZVOMbkgDs+VrX23/aqWS6i9OmZUhf53wujNZdENx",
	"3M7K5EcO3gWq0nlMnHS5Lmpnf4fWZT/OJy464Fksm6ERjdx26bNph5r7Q3gw33KLL5m66ktwl7JduRbi",
	"QzGhBI3+ACHZYpSR6i6tLQtu64FTs4uRDtDVZMF+2LY9x3Zr2NYVp2noNep0lw9kYoLuiJpwdluD1CWq",
	"jtNqHwVaHzY2BCJlpTmcstkBwWflGK0hkpnns1pMw7GdfkmijhHjAeiccPf0WMDYsqEUqbx/BKo5Dj9n",
	"mKhagxgCV3eg2IhJ8ryBiUz+R4qRYGs/dn/saguLtU7h9lJl+Qqh4zKa9lPJF5QrNXeu+EGR2W1aDyl8",
	"Z++ypuMW1j1bxPMm84A7Syp7mwzhG5cEkQDNqWT201ZiVtUbtr/67I8MJ6jkXrBWFFdWgLgyoxCAaU4P",
	"PJMcNhUERPMZIw4VGhQRgSALNSRvjzFjLjqyEsuHAT/B9RyIzygzLdLm/lmpdS1XilXCvSDbxXCYOR07",
	"yKNJHjvS3ldnNqTPZfXzoOe0R2ZsDvYHa4tx3wyWcz9NADDirJMqO/DouywTM5QPFyJq/TrZTB7uVFm8",
	"QcgS6IHT9XWQsydYhqPa3YhpLJ3cE1N9GXubaElR65RO+CI1ksnMx6e6J5j2ipPDnQlSyKq3fC3xGvFD",
	"FiWisFYueBMUr+BmpBVpC/IzVRkU/Z1hP3Fugia3hbkiSnEHRBy72VjeSGZy5Awr9ctXNAfgW/OwIfG2",
	"n5vqUjnmEOnMtSQKlLhBr2WJOFvjgApLwGE1RX4BJZ1Fsblomr8mvMU0HC0ndZb3pWSvMBFr+467sdZu",
	"OZkon1/wA+o8jn0c1BZy0tsanHpfJDMCmQ7RPEryUzDGWBKKoE/I3V+gjzEOe6fHJouOFtHDEmxXZMgP",
	"/SVqzISnsoihLWqtkYlS/U/iK5r3Qku49k7pnW+9rezFeqNl+fH4SgpTHz+zNfUF+nCvzjWDK5XSylsr",
	"i8wA9WnGqH+WFgUNYFQSUCxhylLhTh0nji0yWdqAaXmra5XKPIFQVX+mh36WtRUKZZBndi9lFW8vsAiZ",
	"hZob8AhoJPqwi6O7tdydEhgvjpleDI6JyFKBxRRZt1z1npn7i1NN+8q5Ocmc0JxzqNIQUEkwSWlN0+kT",
	"1YySmfYOpFQkOC+pA7PUR5ZIR5TNCj0Vcp7d7qOr+aiOX7tv17tUgj+7a0RFBH/NlhEVNJffMrJSfOOI",
	"vXHE3jhil+2IvbHYbyz234PFzrHB5zPkuZYXuxZqXc/xN+8Ancg+3bMtz/a+3fXvx1cfyK343o8+NJIQ",
	"3e/96ENm1Wp2p7MUHwBkxsXe51EfI3aKHvOA3bp550NWtrr+/fID23PWN5cQ0Eiptz2RPj5WeiARO4bm",
	"WX3Xs9c9u3NfP0cpHm/+CUlV9h6uj/24W6lcqdEq1vzWx7aLdxB1hTyEIHx8NmbC+77fpiN/HHe9lcFJ",
	"z7OPSEvYg2oK1GxqneJmAlk30nqZMQeqlLti/D61AICN//atG4kDwcQBenghETLZd1Agwx1GGJjsqJQH",
	"ibgUsSCOf65YFmf51fYLCcgGbn5gex2i5XKpUqpgOb9tu1bbMarGlVKldAWExPLvI+eW78k3q4+MjZya",
	"f04DvqibDiK/KNkCInqAo/ZW4Lkhol+nUUUSC/JlKsejT0DgV80VOOEz6k6Usi/OKR5g56nkkc9ZAZQ7",
	"H/HXeDLYU5hKOZYgtGzCDxVnGYUDmJR2GnLWAcikDYpUflHquHRqlzzNSPdKpgK4qZQ0EgexssLN28Vq",
	"BGf8JJ7FpR+GrGOxBeSkoB55OVJ6/wnknvGC0sxcFElskfsXM4gmSeCsEZ8IKRiRL4FkGpUY/5U8Gjqx",
	"0UrsMAt3CfdcFv1xss4DWyibU5LY1zSrIFqtbVNR70bdqBrfdzq+Ii/qed853VXxI+WM47W3zLlvKWc4",
	"L/C0eljy1mriaOKVSmWBk98WO4At62SO7KMlczSALvCgaq5WlvNGjZZR1s4RxOHEOc3zXtRPrURjLENT",
	"g/+Wz5S+dDwn2rdAsd01ou1eBUe4ld+IiYz6LGqboaYEoceuFkvakcXLpdI1U4/o9KbhsyouBaWXtJhZ",
	"dCFsVVwTEnAMGStUL6WTO3XQ3pCAGDgoWEpRxTmjFYLaU1ZAk+meA3BL8tDcJEoej5ak3qOoY0I/PDfs",
	"kZ2ZUO9JpNawBjvSflNP4E2oT3kAYxyDyfNlcEnULCUi9kCCgKV3MU12MRVwqn0adQV7LuQpIfGLBHw5",
	"EBHHs8Qq9Y6ahbpE2Fef/pJdrbyTf54wdd7hl1Kl6eicX3mGC/bZpbWj1oCaVo8Zfn+66eEoWpCkeSbv",
	"ACU/+ujGPxbj83GT0FMikdqbNJRne6Dt64tzIRGMtIexXOGHH9xeeic6WpnxPyUI8dVnf8K1X9fPd16E",
	"0eJ9UDkgZiFzge0ryfPr79tWHV1jcYB9Qla+1t+BWKWXbbB09c1LMxiZPe1bepgGU91KGa3lv9YczjBb",
	"z+PmMFWchZ2qzDc3yp8BuKhpu1p5Z/5L0Vn18MLyAhPD463h4ZWVRaaUPjv20ozuy0jd9ekkGEHybOO7",
	"ZcYBR/lR9CdPtvKDj0W6UkHm9lHIXke9kRPK/w2Vy9h2liVOkQ4ngRuZIPFcmGd8XmtKf37X9nOV52K+",
	"pfxbM9+E65cpNy/UyDl2py4uAlfmvxSffo9vXJ3/RnQ096Xxcs66z8XJZXEiV/VRnp+pneqk+BSCpcrv",
	"3ZGo4ZdxEzoTh6UHAjK0Kw/LRZAhwthEhpCiy3TLfBXs3jILn6AdUntotdPK9EoJ+ayZ6fnc+DR2UovX",
	"RY4oGlY9DatADknOd0wWPhUYSfJ8qXeqSLGjbGYAf0meLzzDU+kEsFI0NyqHJwz5WDp4eLgdOL/qTmQc",
	"Za1m33JOf8jwn3B1/9dVwPPcw/CuxydSpc/RkxgOZZ9NmSQjRCniApl2ENn/Yr1yfuv9NzfIMVOPFjPJ",
	"SkYbOVTNZd9dBQ7s2N6DbP//lteqd2twoeJuD1D+sJFzCXQJGtXXsgxsmEbXa4hUcKdaLlttp2S17YdL",
	"H1ue77gbJVEdKD9Yzmi6u+NbG467IQGXokglDwKfP1qH3l86c9TViFSL5qdjNz6i7dbq1v8EAAD//99R",
	"ieZcbgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
