-- Устаревший алиас. Используйте:
--   docker compose -f compose.yaml cp seed/demonstration_base.sql db:/tmp/demonstration_base.sql
--   docker compose -f compose.yaml exec -T db psql -U apex -d apex -f /tmp/demonstration_base.sql