// Package slotsapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package slotsapi

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for ErrorCode.
const (
	ErrorCodeAlreadyCancelled       ErrorCode = "already_cancelled"
	ErrorCodeBadRequest             ErrorCode = "bad_request"
	ErrorCodeDoubleBooking          ErrorCode = "double_booking"
	ErrorCodeForbidden              ErrorCode = "forbidden"
	ErrorCodeIdempotencyKeyConflict ErrorCode = "idempotency_key_conflict"
	ErrorCodeInternalError          ErrorCode = "internal_error"
	ErrorCodeInvalidCode            ErrorCode = "invalid_code"
	ErrorCodeNotFound               ErrorCode = "not_found"
	ErrorCodeSlotCancelled          ErrorCode = "slot_cancelled"
	ErrorCodeSlotFull               ErrorCode = "slot_full"
	ErrorCodeSlotStarted            ErrorCode = "slot_started"
	ErrorCodeTooManyRequests        ErrorCode = "too_many_requests"
	ErrorCodeUnauthorized           ErrorCode = "unauthorized"
)

// Defines values for RouteType.
const (
	RouteTypeExperienced RouteType = "experienced"
	RouteTypeNovice      RouteType = "novice"
)

// Defines values for SlotStatus.
const (
	Cancelled SlotStatus = "cancelled"
	Scheduled SlotStatus = "scheduled"
)

// Defines values for ListSlotsParamsRouteType.
const (
	ListSlotsParamsRouteTypeExperienced ListSlotsParamsRouteType = "experienced"
	ListSlotsParamsRouteTypeNovice      ListSlotsParamsRouteType = "novice"
)

// Error Стандартное тело ошибки.
type Error struct {
	// Code Канонический машинный код ошибки (R-023). Доменные коды: slot_full (нет свободных мест), double_booking (повторная бронь того же слота), slot_cancelled (слот отменён клубом), slot_started (слот уже стартовал), already_cancelled (бронь уже отменена), invalid_code (неверный/истёкший OTP). Идемпотентность: idempotency_key_conflict (повтор ключа с другим телом). Транспортные/общие: bad_request (400), unauthorized (401), forbidden (403), not_found (404), too_many_requests (429), internal_error (5xx).
	Code ErrorCode `json:"code"`

	// Details Необязательные машиночитаемые детали для динамических сообщений на клиенте (foundations §6): например, актуальная доступность для E1/E2, чтобы показать «Свободно: N мест» / «Свободно: M комплектов экипировки» без разбора текста message.
	Details *struct {
		// AvailableRentalGear Сколько прокатных комплектов экипировки реально свободно (для нехватки прокатных комплектов экипировки).
		AvailableRentalGear *int `json:"available_rental_gear,omitempty"`

		// AvailableSeats Сколько мест реально свободно на момент ошибки (для slot_full / превышения мест).
		AvailableSeats *int `json:"available_seats,omitempty"`
	} `json:"details,omitempty"`

	// Message Человекочитаемое сообщение об ошибке.
	Message string `json:"message"`
}

// ErrorCode Канонический машинный код ошибки (R-023). Доменные коды: slot_full (нет свободных мест), double_booking (повторная бронь того же слота), slot_cancelled (слот отменён клубом), slot_started (слот уже стартовал), already_cancelled (бронь уже отменена), invalid_code (неверный/истёкший OTP). Идемпотентность: idempotency_key_conflict (повтор ключа с другим телом). Транспортные/общие: bad_request (400), unauthorized (401), forbidden (403), not_found (404), too_many_requests (429), internal_error (5xx).
type ErrorCode string

// Geometry Геометрия трассы для отрисовки линии на карте Яндекс.
type Geometry struct {
	union json.RawMessage
}

// Geometry0 Массив координат точек трассы.
type Geometry0 = [][]float32

// Geometry1 Закодированная полилиния (encoded polyline).
type Geometry1 = string

// Instructor Маршал-инструктор, ведущий заезд (брифинг и контроль безопасности).
type Instructor struct {
	// Id Идентификатор маршала-инструктора.
	Id openapi_types.UUID `json:"id"`

	// Name Имя маршала-инструктора.
	Name string `json:"name"`
}

// PaginationMeta Метаданные постраничной выдачи.
type PaginationMeta struct {
	// Limit Размер страницы.
	Limit int `json:"limit"`

	// Offset Смещение от начала выборки.
	Offset int `json:"offset"`

	// Total Общее число элементов.
	Total int `json:"total"`
}

// Route Конфигурация трассы заезда (короткая новичковая / длинная опытная). Справочник, доступен только для чтения.
type Route struct {
	// CapacityCap Потолок числа мест на трассе. Новичковая — не более 8, опытная — не более 14.
	CapacityCap int `json:"capacity_cap"`

	// Description Описательный текст конфигурации / заезда для карточки слота (SCR-003). Опционально; может отсутствовать или быть null.
	Description *string `json:"description"`

	// DurationMin Продолжительность заезда в минутах (обычно 15–20, включая инструктаж).
	DurationMin int `json:"duration_min"`

	// Geometry Геометрия трассы для отрисовки линии на карте Яндекс.
	Geometry Geometry `json:"geometry"`

	// Id Идентификатор конфигурации трассы.
	Id openapi_types.UUID `json:"id"`

	// Name Название конфигурации трассы.
	Name string `json:"name"`

	// Type Тип конфигурации трассы — новичковая (novice) или опытная (experienced).
	Type RouteType `json:"type"`
}

// RouteType Тип конфигурации трассы — новичковая (novice) или опытная (experienced).
type RouteType string

// Slot Полная карточка слота (конкретный заезд на дату/время). Доступен только для чтения. Статус «Прошедшая» — производное значение по полю start_at, отдельным статусом не хранится.
//
// Доступность (R-013): максимально доступное к брони число мест max_seats = min(free_seats, route.capacity_cap, 5). Число прокатных комплектов экипировки в брони ограничено: rental_count ≤ free_rental_gear. Клиент со своей экипировкой занимает место (free_seats), но не расходует прокатный фонд (free_rental_gear).
//
// Цены (R-010): price — тариф за место, rental_price — отдельный тариф проката за экипировку, оба в рублях (валюта RUB). Итоговая цена брони производная = price·seats_count + rental_price·rental_count.
//
// Инварианты: free_seats ≤ total_seats; счётчики (free_seats, free_rental_gear, total_seats) и цены (price, rental_price) неотрицательны.
type Slot struct {
	// FreeRentalGear Число свободных прокатных комплектов экипировки из общего фонда (расчётное). Ограничивает rental_count в брони (rental_count ≤ free_rental_gear). Своя экипировка фонд не расходует, R-013.
	FreeRentalGear int `json:"free_rental_gear"`

	// FreeSeats Число свободных мест (расчётное). Своя экипировка клиента тоже занимает место. К брони доступно max_seats = min(free_seats, route.capacity_cap, 5), R-013.
	FreeSeats int `json:"free_seats"`

	// Id Идентификатор слота.
	Id openapi_types.UUID `json:"id"`

	// Instructor Маршал-инструктор, ведущий заезд (брифинг и контроль безопасности).
	Instructor Instructor `json:"instructor"`

	// MeetingPoint Адрес или ориентир места встречи.
	MeetingPoint string `json:"meeting_point"`

	// MeetingPointLat Широта места встречи.
	MeetingPointLat float32 `json:"meeting_point_lat"`

	// MeetingPointLng Долгота места встречи.
	MeetingPointLng float32 `json:"meeting_point_lng"`

	// Price Цена за одно место, в рублях (целое число, валюта RUB).
	Price int `json:"price"`

	// RentalPrice Тариф проката за одну экипировку, в рублях (целое число, валюта RUB).
	RentalPrice int `json:"rental_price"`

	// Route Конфигурация трассы заезда (короткая новичковая / длинная опытная). Справочник, доступен только для чтения.
	Route Route `json:"route"`

	// StartAt Дата и время начала заезда.
	StartAt time.Time `json:"start_at"`

	// Status Статус слота.
	Status SlotStatus `json:"status"`

	// TotalSeats Общее число мест в слоте.
	TotalSeats int `json:"total_seats"`
}

// SlotListResponse Постраничный список слотов (SCR-002).
type SlotListResponse struct {
	// Items Элементы списка слотов.
	Items []SlotSummary `json:"items"`

	// Meta Метаданные постраничной выдачи.
	Meta PaginationMeta `json:"meta"`
}

// SlotStatus Статус слота.
type SlotStatus string

// SlotSummary Урезанное представление слота для списка (SCR-002).
type SlotSummary struct {
	// FreeRentalGear Число свободных прокатных комплектов экипировки из общего фонда (расчётное). Ограничивает rental_count в брони (rental_count ≤ free_rental_gear). Своя экипировка фонд не расходует, R-013.
	FreeRentalGear int `json:"free_rental_gear"`

	// FreeSeats Число свободных мест (расчётное). Своя экипировка клиента тоже занимает место. К брони доступно max_seats = min(free_seats, route.capacity_cap, 5), R-013.
	FreeSeats int `json:"free_seats"`

	// Id Идентификатор слота.
	Id openapi_types.UUID `json:"id"`

	// Instructor Маршал-инструктор, ведущий заезд (брифинг и контроль безопасности).
	Instructor Instructor `json:"instructor"`

	// Price Цена за одно место, в рублях (целое число, валюта RUB).
	Price int `json:"price"`

	// RentalPrice Тариф проката за одну экипировку, в рублях (целое число, валюта RUB).
	RentalPrice int `json:"rental_price"`

	// Route Конфигурация трассы заезда (короткая новичковая / длинная опытная). Справочник, доступен только для чтения.
	Route Route `json:"route"`

	// StartAt Дата и время начала заезда.
	StartAt time.Time `json:"start_at"`

	// Status Статус слота.
	Status SlotStatus `json:"status"`

	// TotalSeats Общее число мест в слоте.
	TotalSeats int `json:"total_seats"`
}

// DateFromParam defines model for DateFromParam.
type DateFromParam = time.Time

// DateToParam defines model for DateToParam.
type DateToParam = time.Time

// InstructorIdParam defines model for InstructorIdParam.
type InstructorIdParam = []openapi_types.UUID

// LimitParam defines model for LimitParam.
type LimitParam = int

// OffsetParam defines model for OffsetParam.
type OffsetParam = int

// OnlyAvailableParam defines model for OnlyAvailableParam.
type OnlyAvailableParam = bool

// RouteTypeParam defines model for RouteTypeParam.
type RouteTypeParam = []string

// SlotIdParam defines model for SlotIdParam.
type SlotIdParam = openapi_types.UUID

// BadRequest Стандартное тело ошибки.
type BadRequest = Error

// InternalError Стандартное тело ошибки.
type InternalError = Error

// NotFound Стандартное тело ошибки.
type NotFound = Error

// Unauthorized Стандартное тело ошибки.
type Unauthorized = Error

// ListSlotsParams defines parameters for ListSlots.
type ListSlotsParams struct {
	// DateFrom Фильтр: слоты со стартом не раньше указанного момента (граница включительна), R-026. По умолчанию — текущий момент (R-027).
	DateFrom *DateFromParam `form:"date_from,omitempty" json:"date_from,omitempty"`

	// DateTo Фильтр: слоты со стартом не позже указанного момента (граница включительна), R-026. По умолчанию — date_from + 7 дней (R-027).
	DateTo *DateToParam `form:"date_to,omitempty" json:"date_to,omitempty"`

	// RouteType Тип маршрута (множественный выбор). Значения внутри группы объединяются по OR; между разными группами фильтров (route_type, instructor_id) — AND (R-026).
	RouteType *RouteTypeParam `form:"route_type,omitempty" json:"route_type,omitempty"`

	// InstructorId Идентификаторы инструкторов (множественный выбор). Значения внутри группы объединяются по OR; между разными группами фильтров — AND (R-026).
	InstructorId *InstructorIdParam `form:"instructor_id,omitempty" json:"instructor_id,omitempty"`

	// OnlyAvailable Только слоты со свободными местами (free_seats > 0). По умолчанию false — показываются все.
	OnlyAvailable *OnlyAvailableParam `form:"only_available,omitempty" json:"only_available,omitempty"`

	// Limit Максимальное число элементов в выдаче
	Limit *LimitParam `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Смещение от начала выдачи
	Offset *OffsetParam `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListSlotsParamsRouteType defines parameters for ListSlots.
type ListSlotsParamsRouteType string

// AsGeometry0 returns the union data inside the Geometry as a Geometry0
func (t Geometry) AsGeometry0() (Geometry0, error) {
	var body Geometry0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromGeometry0 overwrites any union data inside the Geometry as the provided Geometry0
func (t *Geometry) FromGeometry0(v Geometry0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeGeometry0 performs a merge with any union data inside the Geometry, using the provided Geometry0
func (t *Geometry) MergeGeometry0(v Geometry0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsGeometry1 returns the union data inside the Geometry as a Geometry1
func (t Geometry) AsGeometry1() (Geometry1, error) {
	var body Geometry1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromGeometry1 overwrites any union data inside the Geometry as the provided Geometry1
func (t *Geometry) FromGeometry1(v Geometry1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeGeometry1 performs a merge with any union data inside the Geometry, using the provided Geometry1
func (t *Geometry) MergeGeometry1(v Geometry1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Geometry) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Geometry) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Список слотов с фильтрами
	// (GET /slots)
	ListSlots(w http.ResponseWriter, r *http.Request, params ListSlotsParams)
	// Карточка слота
	// (GET /slots/{slotId})
	GetSlot(w http.ResponseWriter, r *http.Request, slotId SlotIdParam)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Список слотов с фильтрами
// (GET /slots)
func (_ Unimplemented) ListSlots(w http.ResponseWriter, r *http.Request, params ListSlotsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Карточка слота
// (GET /slots/{slotId})
func (_ Unimplemented) GetSlot(w http.ResponseWriter, r *http.Request, slotId SlotIdParam) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListSlots operation middleware
func (siw *ServerInterfaceWrapper) ListSlots(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListSlotsParams

	// ------------- Optional query parameter "date_from" -------------

	err = runtime.BindQueryParameter("form", true, false, "date_from", r.URL.Query(), &params.DateFrom)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "date_from", Err: err})
		return
	}

	// ------------- Optional query parameter "date_to" -------------

	err = runtime.BindQueryParameter("form", true, false, "date_to", r.URL.Query(), &params.DateTo)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "date_to", Err: err})
		return
	}

	// ------------- Optional query parameter "route_type" -------------

	err = runtime.BindQueryParameter("form", true, false, "route_type", r.URL.Query(), &params.RouteType)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "route_type", Err: err})
		return
	}

	// ------------- Optional query parameter "instructor_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "instructor_id", r.URL.Query(), &params.InstructorId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "instructor_id", Err: err})
		return
	}

	// ------------- Optional query parameter "only_available" -------------

	err = runtime.BindQueryParameter("form", true, false, "only_available", r.URL.Query(), &params.OnlyAvailable)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "only_available", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListSlots(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSlot operation middleware
func (siw *ServerInterfaceWrapper) GetSlot(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "slotId" -------------
	var slotId SlotIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "slotId", chi.URLParam(r, "slotId"), &slotId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "slotId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSlot(w, r, slotId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/slots", wrapper.ListSlots)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/slots/{slotId}", wrapper.GetSlot)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xc724bR5J/lcbcfSCxI5KS7fyhkQ/ObbLwYjc2bC/2gyMQY7Ilz4acYYZDwzrDgEit",
	"rfjkteKNgV0El+wlt0gOCA5H0aJFkRIF6Am6XyFPcqiq7pnp4VCiZB8OhzOQGJ7h9J/6/6vqaj+wqn6j",
	"6XvcC1tW+YHVdAKnwUMe4NMvnZB/HPiN6/AWXtR4qxq4zdD1Patsib+LoRjLp7Ir18tMdsRYTGRXbsFf",
	"J0x2ZFf05Lrsiok4YOJQDJhcFz1xKJ/KL+BhQ4xET+zBK3EoJuKlmDBxAF+LgTiE0SwnXtIYMZSPRY+J",
	"vhiJsXwmN8VQdsUAlheHope32Y2F0tI7BSb+Bmtv4DxjuanGPmM/r79gOGIkN+QTMRT7xlosB+PfzRcs",
	"23KBuM/bPFizbMtzGtwqWzUn5JWVwG9YttWq3uUNB/ix4gcNJ1Q/L4Rug1u2Fa41YUQrDFxv1Xr40EY+",
	"3vLfGBfFkZiIPfHqf4WHESPYL9i7TOzCjsT+XOwL/fMw76rXCoN2NfSDq7VZLPyr2FXkDuUfxRB4AgyT",
	"63KLiaE4BC7KdWAWvRYT0Wc5cYAseyUGyOU+TCEO5RaoRl9uiR34NF9g4i/AHrmJvw/lNnDwUG7AlGLI",
	"gLtyQxyJI1hsInbkv4iB2MVlt+Uz2ZUdGHIkJuzajcsMBfNK7MoNsoY9XPHAmEj08AWSojQDdwz8v/LJ",
	"L4nZ7yCz+f1m3a9xqxwGbZ7NezdiYMWtGRJwQ95oGaJot/GTlBSiF04QOGvw3ArX6vACBsLzb9yGG86S",
	"zr+KnhjJjhiKA9FT2jYB5QUFRH1n8k9iLAaR0gKx+J/cErvE+hmKVYeFDaJqfMVp10OrvFSyrYZz3220",
	"G1Z5sQRPrqeeIopcL+SrPEBNu7ay0uIzqfgOdiefkBKAFU5klynF6IkxGla03eGM7fq4RPZ+kxssZW/Q",
	"q69duee4dedOnc/a5/dotE/FCL1H2puIPqiomIDhar07UAZAWpdbCTivtLgTttin7VLpAmel/GyfsOLU",
	"Wxw1E90SeiO5JfqiF+t+X3bEYJZr8L36WsXRVGWzBheJWHLH9+vc8ZAlN/x2yG+tNU9gx1AcAY3gRL8A",
	"C1NO8f+a8ecCILUCPLCZYdP5czqGeMJsr8A9UMXbluffc6uc5uSBy70qr1nL5/ASN+t+eA4nHqmx6Gkd",
	"ajrh3ZiQFs5r2VbAP2+7Aa9pqjOCTbaHA1UKeKvpey2OtH/o1G7wz9u8FcJT1fdC7uFfnWaz7lYd2HTx",
	"Dy3Y+QOL33caTaAUvqyhijq1SqDG21aDt1rOKrwX34gB6JpcR8ljLO+hKoARdilgQTQ/AqnLjuiB5ZEG",
	"wCjQBxg1wuC2jnCmC4qMEe4pTDfA17uECOSWfAQTJlRY7BdQNhFr/jHgK1bZ+odiDAWL9Gur+FEQ+AGx",
	"JyWtMxPCcrALfB7iR+s2Qy9TqfptL0S7gnnAeHpoBntiAkPYYqFwCcL4WAxZwL3QqeshO+TrEE4m5soj",
	"hVe9kAeeUycaziNFV81Q4TiFIcgfQTcX4A80b/kFxjFCueBKR+QyiX6xIzfEPoluIJ/I58r8E1DujQjl",
	"z5FrIm+2Dc4H9jYUO2BPYEkgsj4G3h6u+Ykffuy3vdq5OOT5YWUFRxvM+YsSdA+X7osexHb0rbA12ZEb",
	"cl12FJoFrdgn238jTHitxX/nOe3wrh+4/8zPx5F2cgKDKd+jWEATBjou9ERfAdIhGIt8DBEGFSe2YqU2",
	"sMV9FaoSsJ3o6mLkHYhDRE1gdi/BMtBrjMSAXVFbws2/ESZ/iyRs4J9d0SeitJFiTtBXNBwa28ugWAwL",
	"GMrVorCnyGTTGAxN6xBB1jo5PrK3AVlfrOpDiIHNwG/yIHTJpZOApub8GmecYHTfBP2A0ZQdkgZFsGAE",
	"sMlYhALuBYAJL3TOpf0hfi23ygyiU2WlXa+jBwQ2pWEY+GgFwvI2q/ntO3VeueP7n7neKsuhj9BcA0e+",
	"zcQOepVD+ZSYi1kf5oNRpMzbtHDV8aq8Xuc1ltM/InRVWPs5CAXSwQ3czoEe1gqdIDQGyQ21QiIhBeMa",
	"523m1APu1NaSiyW3SCPjVfF/2KHr3XPqbq0CoiHuJGLKfhG8lOzK52KELN9n125dB14TUjhAv9tVmCGK",
	"gWXm1nij6Yfcq65VPuNrlarvrdTdamiykkVZMLhFJnYRgL2E4BRplDiA5b5XZYsOLoh6ByIuol9/AslA",
	"mSUCPstdLJXyNkt6Ani3mLfZih/ccWs17sGLC3mbRQ4UXlzM2yz0/UrD8db0bC2Wu7j0PvIqGYxY7tL9",
	"+wT0FEqL1MyyLVOFAN0ZqqBfKCFbtjUlQARasXDgcQZXLTuFdlIeMCIZ8FoiXEwRiksaAXfZjh2sQd8U",
	"8qzx0HHrrQzzBpwCctpGd5P0m4OkiU9UNUQHC/K4+AI92q4Yg90hsieEHjsL+QizK6UOCmRhaEEdAwVB",
	"FR2wHBKPXrjFjn98J19m06AIs+Wu3Ihy5R6tTPoNOUIC79G+PlosfrRkM7mJVrkD2CtKxoBq+ZQd/yS+",
	"S3odMSmzTyK3czxmxcxPfkuODGxtrNAmJCPyT+glj8RQYdORGB6PAZANxJ7ObTCFAuuishs6DqYC4rR7",
	"jlLAisJ4q9zJjAG4IZ3hKnxFuYJypfNuGPFAXJFIuWUxYTktdnDbjzCn7eLA11lVZWdKrTMqEXaCFQhq",
	"T2eCkuKpBJFOJsueZjRT9MYRq0ikDiAlBpStc2AdrQxaljKLFuqVf+cPvBoCdREkmqLqR+V1IRkfmSZJ",
	"gT5tZQPMuZNEDIwdWaZCG5HWzB4oMhcyK5BxVnnbUs5Q07CcQd+vuN/gYbCWQeBX6IxUhoScxL/0ZEd2",
	"wGiVuk3Uz51IU9GLAMXDyK9QDB4w8V8IiNDCYP++x6+tWOXbWWU4WAcwMWkrWKdyaKA7XeT4QIyMTWHZ",
	"RlcEpqBTahIsgkEmN4QdqZxQbrHbdSe0Wd1bXTamU6zz2o07pPgN5/5V+nEJi2HxQ7q0kHp+kJUEIAKL",
	"TI8q5D1VjkGGKqbKbZbjHki2xpp+fa3uejyfoQrLRjU6u9Ap1+UXYIELWWVnm6Fq78YnEHuo3XtiVwEm",
	"qnwcipcMJD1CAEUFoDF4e3SvkFSCdHQYUC7F9KZu7UwVFl0fo0pm5uYhXbRPrxRTSSZj6QPyG/Mtk7Dg",
	"L5VH7UACdKp94qZwD1mmed1ZdT0Mv7/loZMpQYr5UflEHbfQLlXRcxPzhX2j3jstAapMTy/xbxgbMdYz",
	"Y9rHZGyxOy1lxQZVQT53fZqCskqQorUylwr90KlnrPSt8sCnVPCNBS5mB4ek6HQpP6qR0/pZcsSq7wyH",
	"dIiq/RKyfJ1Rp7xsZHRYlBrRgRBG9h4F+wnm2Jtof318WUTfTMkgfTURR3IL846e3IYs4TsqOkC8QQ0Z",
	"ipFtwrYoF47iNvl7hG0qtGakrU7TqbohYPNmBsl/w61Tsj+KBdJLxLlDxGCaA2JQYOKbDBqxho9FEQyM",
	"KOD37BSlmV8tXjRk/V6WMhnbzlCpIypJTVc2FHTU3jAlXDEE2SQlqoOojpATJHKYSI1Z7uY/3VgolTBv",
	"/1Yc4TxYatTI6TKBpFdU1JiYtQ7FMITfqt6xAwyST5nXrtdT7uvrtHqNZuhojDUN0ZRBpj0N90dx6o1J",
	"6yRxtqvruwNIYDuRXmOEsA3Xq8PQc0RBZtiJCsipo2cgC8jDQxpVXp9Ow9oBetdKw82SMhWyd1FvXhmH",
	"z1E+Y0iyD7seUk1T9OQjlqPshjwwW7z08/pXSyU7eaKNLE6HlZ54lULdmSq6mgBuJ1XFIoD30D5znJ2l",
	"xGnIdd44+w1GF0I7Q12GmmfBk1Q2wyPOPiQ+mXfRed0JkVvNZJuuL6VdCXHNjBC31IayjwTn4Yx2d9Pe",
	"MkenYvnIB5huMpc4KzPKNHMfpt2s+2G2vxdjHYRMH9czfBzRJ0ZY9O7qGmYMOCmP2EVPtlEUfbT6A4pl",
	"L84atRiVZmGI7LDjn8jUMWPcBZ8jt4/H6pAYfcAQlVSlpaCm5hEVgS4F1OUzhoWqCuQQSN1uIkYcaD+F",
	"SydajR5FjhGL7YVPvU89g7DY6+RuLJQWL+TL6CSnWxWmii9oV1ERFlQmxkFR2G0499Up+ges4XqJY3Wb",
	"4clrIaneNrsEjP8xnud1ChvgOePdZUSJSdk8Sfv5yd8ZbjBReykw8XVcvTIaCAYQmqcXnmgNO1QMxPCp",
	"2wsmydaCvM10RYLawmRHPsKKuTpJSJEPC/4R6dlV0yR2mifh/oA73SJxlvJl1gzcKtedXz2Kc7jBxKZs",
	"zYj44ykd2zfGJ3fWo+mmeSE3EDntUBjDSLQDZoNBDMvm8hmOv/G7D7Gkrev4yr3Ix1QkN+Q4bTvw6QdE",
	"5/Fe8jT1FwZZx3tJaRO3/ioOca11PG+FNHOrzBK9H6ASiMDp+TLY2SZABlB2KhclVTotEzs5GLykIgnk",
	"g3syGZ+nQyNd+XhsIsFpVJxeLrOaFOUmGectr2VeQ7HHokLUS1hB6SY4XqXNyCvyFoQzkzaoziVlN3Wg",
	"bdht7lQTpbwDMo7trJ32YpuZYWfY8rd4wQAA757ch2RbsdjPzHXtHGcw6URajFp6j2LSK4odszwOuDDD",
	"glKO/BxOOotjl07j2BlRYhzG54KCrlGTOgl9JapXWIjloeutVpq+62VBjS/FLp2YxxgHvYXe9HqidQyb",
	"vKjzQJdDDERJOAVzjAXlCLpyHZDCl4gxRrJzPLZZ1PNhpiUg7g2G+tBdQPvch6+ymGEQVak7WYT9B+kV",
	"7XsuEi69X3j/3fcSslip+04Yr58oYZrre6sZ679ADPfyTDu4UCosvbM0zw7Qn2as+oOOKBgAoyOBRCSc",
	"ilQoqXGqWRPzrVQAM+pWl0ql0wwi6fozEfpJ0VY5lI1ZYfeNUPHeHEToKtSpCQ81wxGGzdQHRR0gN43D",
	"U7W7RGJsOIUTmqdxzbDdOm2LkGncpC911W+me8+s/cWlpn7suwbpmtAp3bdTuWDEMM1pw9OZGzWCkj2N",
	"DrRVpDQv7QOz3EeWSUeczUo9gZ2/cVvhDdVPOKNol6ooE8zsqDoY1vI0J7H7k0pWS1ml/hmnM/+ZLMhS",
	"BzBNbmSKqlAbTXKqorQbDSfIOoOxGqqmftIUqQr8lOBxG2qqWcy9GWl1VnuQykHNGBo1SVTv8lqb+hvi",
	"XodZ6bemdXqlf0crja9dDPQ56a7qpO4j8ymXTWTlOndOiuIE0b5FuW9R7luU+3oo9y0ceguH/j/AoRkA",
	"52woaSasAe7xajtww7WbwCeKT3e4E/DgSju8Gz99rEXx69/fstJ9w7/+/S3mVKu81VqIu4Lt+CT9eeLG",
	"DLJuwK5fu3mLFZ12eLd4jwfuytoCdotSXXNH1ebHcjvqqsbGPAzPybEBXwl4667ZXB2vd3rbdJl9iPTR",
	"pagqUVEJ/c+4R9ekCvoWDV4AwW9jJbwbhk1qpHa9FX/W2ZjsiAOqgZnoj+KIPiPVPSsBd2oLvldf024B",
	"AjoeJuYZIKDkDSK6VIRFRCSTGnYeY6TZx8Jz4owxCkB0jIix/8r1q6nbA+p+Bz7otqTsN2iocotR41F2",
	"KUAMUsUAbMBxwzMVEHCXP6+/YGDDoOL3eNAiBi8WSoUSNlA0uec0XatsXSiUChfAcpzwLqpzsYXDyg+s",
	"1cwWiz/jZY0+SuOJDsNJ3DeR29QQnLx5l5uWno7n5MEmon9GgUWY0WYf3lwolRYJVugVgQOzlWP2XT7z",
	"Kt4HdLUvd8q9Poow3YLcLOj+z8gBYum9Q+c42PWmDgmOf8JOG9WdMMD+04x+WQVDlpA46rw2oNKRmERH",
	"Q+rECLDYnoJd3YgwfTtZnQENEDCO41Ox1J0jo7NHDy4z7Pcdi2HiDjR1QuzpjqHTbplfTs0R+pkzZN+x",
	"LjDxVbJZSB3ezbjPja1L+j4gE98mO/7Vr0kdJcf/QZQT5UloR7QvELl5IRfgRkc1ZNL1yfgqiHyGpE+f",
	"zF1OoNREV95QXcRh+P4RnQSkMWzu4mIJIQnkR+iQr9assgWJtjb25D9ecDs7xsefFM1/3OChPdcAfYt/",
	"js9TN1PnGDF9032OQRl3gucYlbivPc8aiYvRD5dTNyWXSqU5LkrNd99oqnSSdfXouxk1EnDuF2kzWWtE",
	"my4m7nbikMXThxjXwnBL6mbyaQPNS4gIo3RRYTYl2cEA4qGzCrptkcYvw3QUs4oP6A7sw9nBSzUO6LsN",
	"vSk3cELvFIUbOiIfzdNjR5eVMarpNg07eRJsFroxRoymm4mBajs6N7RnXoKI8PbrdeZPe5dfcXQuZ/Yt",
	"yYvO/+MGk2kkLzIFfG59v1i6ePqg6CbpGzOQr2f2t2QZQyJHQSEls5PbyyCHFg/uaRGaDLse+LV2FR6S",
	"bSq72A6C9x4WQKswkX6lC3uWbbWDugL3rXKx6DTdgtPk9xc+c4LQ9VYLKt8r3lvM6FG/GTqrrrcaYQYy",
	"DeqvYHOs1qLxCyeuuhzxKaNhWEX/YhZAtWMEGV+0J1Y/XH743wEAAP//ZAJM4jhIAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
