// Package authapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package authapi

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for ErrorCode.
const (
	ErrorCodeAlreadyCancelled       ErrorCode = "already_cancelled"
	ErrorCodeBadRequest             ErrorCode = "bad_request"
	ErrorCodeDoubleBooking          ErrorCode = "double_booking"
	ErrorCodeForbidden              ErrorCode = "forbidden"
	ErrorCodeIdempotencyKeyConflict ErrorCode = "idempotency_key_conflict"
	ErrorCodeInternalError          ErrorCode = "internal_error"
	ErrorCodeInvalidCode            ErrorCode = "invalid_code"
	ErrorCodeNotFound               ErrorCode = "not_found"
	ErrorCodeSlotCancelled          ErrorCode = "slot_cancelled"
	ErrorCodeSlotFull               ErrorCode = "slot_full"
	ErrorCodeSlotStarted            ErrorCode = "slot_started"
	ErrorCodeTooManyRequests        ErrorCode = "too_many_requests"
	ErrorCodeUnauthorized           ErrorCode = "unauthorized"
)

// Defines values for PushTokenDeleteRequestPlatform.
const (
	PushTokenDeleteRequestPlatformAndroid PushTokenDeleteRequestPlatform = "android"
	PushTokenDeleteRequestPlatformIos     PushTokenDeleteRequestPlatform = "ios"
)

// Defines values for PushTokenRequestPlatform.
const (
	PushTokenRequestPlatformAndroid PushTokenRequestPlatform = "android"
	PushTokenRequestPlatformIos     PushTokenRequestPlatform = "ios"
)

// Defines values for TokenPairTokenType.
const (
	Bearer TokenPairTokenType = "Bearer"
)

// Client Клиент сервиса. Аутентифицируется по номеру телефона (логин в формате E.164). Сразу после регистрации (verify-code, is_new=true) name ещё не задан — пустое/отсутствующее имя означает незавершённую регистрацию (дозаполняется через PATCH /profile).
type Client struct {
	// CreatedAt Дата и время регистрации клиента.
	CreatedAt time.Time `json:"created_at"`

	// Id Идентификатор клиента.
	Id openapi_types.UUID `json:"id"`

	// Name Имя клиента. Отсутствует у только что зарегистрированного клиента до шага 3 (PATCH /profile).
	Name *string `json:"name,omitempty"`

	// Phone Номер телефона в формате E.164. Используется как логин. Владельцу в GET /profile возвращается полностью; в любых представлениях, видимых третьим лицам, ПДн (включая телефон) маскируются (R-017, NFR-11).
	Phone string `json:"phone"`
}

// Error Стандартное тело ошибки.
type Error struct {
	// Code Канонический машинный код ошибки (R-023). Доменные коды: slot_full (нет свободных мест), double_booking (повторная бронь того же слота), slot_cancelled (слот отменён клубом), slot_started (слот уже стартовал), already_cancelled (бронь уже отменена), invalid_code (неверный/истёкший OTP). Идемпотентность: idempotency_key_conflict (повтор ключа с другим телом). Транспортные/общие: bad_request (400), unauthorized (401), forbidden (403), not_found (404), too_many_requests (429), internal_error (5xx).
	Code ErrorCode `json:"code"`

	// Details Необязательные машиночитаемые детали для динамических сообщений на клиенте (foundations §6): например, актуальная доступность для E1/E2, чтобы показать «Свободно: N мест» / «Свободно: M комплектов экипировки» без разбора текста message.
	Details *struct {
		// AvailableRentalGear Сколько прокатных комплектов экипировки реально свободно (для нехватки прокатных комплектов экипировки).
		AvailableRentalGear *int `json:"available_rental_gear,omitempty"`

		// AvailableSeats Сколько мест реально свободно на момент ошибки (для slot_full / превышения мест).
		AvailableSeats *int `json:"available_seats,omitempty"`
	} `json:"details,omitempty"`

	// Message Человекочитаемое сообщение об ошибке.
	Message string `json:"message"`
}

// ErrorCode Канонический машинный код ошибки (R-023). Доменные коды: slot_full (нет свободных мест), double_booking (повторная бронь того же слота), slot_cancelled (слот отменён клубом), slot_started (слот уже стартовал), already_cancelled (бронь уже отменена), invalid_code (неверный/истёкший OTP). Идемпотентность: idempotency_key_conflict (повтор ключа с другим телом). Транспортные/общие: bad_request (400), unauthorized (401), forbidden (403), not_found (404), too_many_requests (429), internal_error (5xx).
type ErrorCode string

// PushTokenDeleteRequest Снятие регистрации push-токена устройства (R-006). Токен передаётся в теле, а не в URL, чтобы не записывать сырое значение токена в логи/историю URL.
type PushTokenDeleteRequest struct {
	// Platform Платформа устройства.
	Platform PushTokenDeleteRequestPlatform `json:"platform"`

	// Token Токен push-уведомлений, выданный платформой (APNs/FCM).
	Token string `json:"token"`
}

// PushTokenDeleteRequestPlatform Платформа устройства.
type PushTokenDeleteRequestPlatform string

// PushTokenRequest Регистрация push-токена устройства для напоминаний (R-006).
type PushTokenRequest struct {
	// Platform Платформа устройства.
	Platform PushTokenRequestPlatform `json:"platform"`

	// Token Токен push-уведомлений, выданный платформой (APNs/FCM).
	Token string `json:"token"`
}

// PushTokenRequestPlatform Платформа устройства.
type PushTokenRequestPlatform string

// RefreshTokenRequest Запрос на обновление сессии по refresh-токену (R-016).
type RefreshTokenRequest struct {
	// RefreshToken Действительный refresh-токен, ранее выданный verify-code или refresh.
	RefreshToken string `json:"refresh_token"`
}

// RequestCodeRequest Запрос на отправку OTP-кода на номер телефона.
type RequestCodeRequest struct {
	// Phone Номер телефона в формате E.164.
	Phone string `json:"phone"`
}

// RequestCodeResponse Ответ на запрос OTP-кода. В демонстрационной backend-реализации code возвращается в ответе вместо отправки через SMS-провайдера.
type RequestCodeResponse struct {
	// Code OTP-код для демонстрационной реализации без SMS-провайдера. В production должен отправляться через провайдера и не возвращаться клиенту.
	Code *string `json:"code,omitempty"`

	// ResendAfterSeconds Через сколько секунд можно запросить повторную отправку (по умолчанию 60). Более ранний повтор → 429.
	ResendAfterSeconds int `json:"resend_after_seconds"`

	// TtlSeconds Срок жизни кода в секундах (по умолчанию 300 = 5 минут). По истечении код недействителен.
	TtlSeconds int `json:"ttl_seconds"`
}

// TokenPair Пара JWT-токенов сессии (R-016). access_token передаётся в Authorization для защищённых запросов; refresh_token используется только на /auth/refresh для получения новой пары (ротация).
type TokenPair struct {
	// AccessToken JWT access-токен. Короткоживущий, передаётся в заголовке Authorization.
	AccessToken string `json:"access_token"`

	// ExpiresIn Срок жизни access-токена в секундах.
	ExpiresIn int `json:"expires_in"`

	// RefreshToken Refresh-токен для обновления сессии через POST /auth/refresh. Долгоживущий, хранится только на клиенте.
	RefreshToken string `json:"refresh_token"`

	// TokenType Тип токена.
	TokenType TokenPairTokenType `json:"token_type"`
}

// TokenPairTokenType Тип токена.
type TokenPairTokenType string

// VerifyCodeRequest Подтверждение OTP-кода и вход/регистрация. Только phone и code: на этом шаге ещё не известно, новый клиент или существующий, поэтому имя здесь не передаётся — для нового клиента оно дозаполняется отдельным шагом (PATCH /profile, шаг 3 SCR-001).
type VerifyCodeRequest struct {
	// Code OTP-код из SMS (4–6 цифр).
	Code string `json:"code"`

	// Phone Номер телефона в формате E.164.
	Phone string `json:"phone"`
}

// VerifyCodeResponse Ответ на подтверждение кода — пара токенов сессии и данные клиента (R-016). Для нового клиента (is_new=true) поле client.name пустое/отсутствует: имя дозаполняется через PATCH /profile (шаг 3 SCR-001). Существующий клиент возвращается с заполненным именем.
type VerifyCodeResponse struct {
	// Client Клиент сервиса. Аутентифицируется по номеру телефона (логин в формате E.164). Сразу после регистрации (verify-code, is_new=true) name ещё не задан — пустое/отсутствующее имя означает незавершённую регистрацию (дозаполняется через PATCH /profile).
	Client Client `json:"client"`

	// IsNew true, если клиент только что зарегистрирован (имя ещё не задано).
	IsNew bool `json:"is_new"`

	// Tokens Пара JWT-токенов сессии (R-016). access_token передаётся в Authorization для защищённых запросов; refresh_token используется только на /auth/refresh для получения новой пары (ротация).
	Tokens TokenPair `json:"tokens"`
}

// BadRequest Стандартное тело ошибки.
type BadRequest = Error

// InternalError Стандартное тело ошибки.
type InternalError = Error

// NotFound Стандартное тело ошибки.
type NotFound = Error

// TooManyRequests Стандартное тело ошибки.
type TooManyRequests = Error

// Unauthorized Стандартное тело ошибки.
type Unauthorized = Error

// DeletePushTokenJSONRequestBody defines body for DeletePushToken for application/json ContentType.
type DeletePushTokenJSONRequestBody = PushTokenDeleteRequest

// RegisterPushTokenJSONRequestBody defines body for RegisterPushToken for application/json ContentType.
type RegisterPushTokenJSONRequestBody = PushTokenRequest

// RefreshTokenJSONRequestBody defines body for RefreshToken for application/json ContentType.
type RefreshTokenJSONRequestBody = RefreshTokenRequest

// RequestAuthCodeJSONRequestBody defines body for RequestAuthCode for application/json ContentType.
type RequestAuthCodeJSONRequestBody = RequestCodeRequest

// VerifyAuthCodeJSONRequestBody defines body for VerifyAuthCode for application/json ContentType.
type VerifyAuthCodeJSONRequestBody = VerifyCodeRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Выход
	// (POST /auth/logout)
	Logout(w http.ResponseWriter, r *http.Request)
	// Удалить push-токен
	// (DELETE /auth/push-tokens)
	DeletePushToken(w http.ResponseWriter, r *http.Request)
	// Зарегистрировать push-токен
	// (POST /auth/push-tokens)
	RegisterPushToken(w http.ResponseWriter, r *http.Request)
	// Обновить токен сессии
	// (POST /auth/refresh)
	RefreshToken(w http.ResponseWriter, r *http.Request)
	// Запросить код подтверждения (OTP)
	// (POST /auth/request-code)
	RequestAuthCode(w http.ResponseWriter, r *http.Request)
	// Подтвердить код и войти/зарегистрироваться
	// (POST /auth/verify-code)
	VerifyAuthCode(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Выход
// (POST /auth/logout)
func (_ Unimplemented) Logout(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Удалить push-токен
// (DELETE /auth/push-tokens)
func (_ Unimplemented) DeletePushToken(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Зарегистрировать push-токен
// (POST /auth/push-tokens)
func (_ Unimplemented) RegisterPushToken(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Обновить токен сессии
// (POST /auth/refresh)
func (_ Unimplemented) RefreshToken(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Запросить код подтверждения (OTP)
// (POST /auth/request-code)
func (_ Unimplemented) RequestAuthCode(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Подтвердить код и войти/зарегистрироваться
// (POST /auth/verify-code)
func (_ Unimplemented) VerifyAuthCode(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeletePushToken operation middleware
func (siw *ServerInterfaceWrapper) DeletePushToken(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeletePushToken(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RegisterPushToken operation middleware
func (siw *ServerInterfaceWrapper) RegisterPushToken(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RegisterPushToken(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RefreshToken operation middleware
func (siw *ServerInterfaceWrapper) RefreshToken(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RefreshToken(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RequestAuthCode operation middleware
func (siw *ServerInterfaceWrapper) RequestAuthCode(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RequestAuthCode(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// VerifyAuthCode operation middleware
func (siw *ServerInterfaceWrapper) VerifyAuthCode(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.VerifyAuthCode(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/logout", wrapper.Logout)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/auth/push-tokens", wrapper.DeletePushToken)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/push-tokens", wrapper.RegisterPushToken)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/refresh", wrapper.RefreshToken)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/request-code", wrapper.RequestAuthCode)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/verify-code", wrapper.VerifyAuthCode)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x8XW/bVpr/Vzngfy4klJbk2E0RF71I8093WzRtkHi2F03WYCTa0UQmtSSVjbcwYEnN",
	"G5yJJ50AHRSYZDJz0Yu5kRUzlvVmIJ/gnK/QT7J4nueQPHyTHI/TxSz2okUkkzznPG+/3/NCfadV7c2m",
	"bZmW52or32mO6TZtyzXxw6dG7Zr5Hy3T9eBT1bY808J/Gs1mo141vLptlX/n2hZ8Z94zNpsNk66smdqK",
	"dsuorTnyfl3bNF3X2IDv+Z+5z/vcFzt8Ina5z/gx74kd3uNj7ouO2BG7jB/yHj8WO3wq2rxXYvwl/Jvu",
	"Ek9EB+4a8qnYETvc50PR4RO4VHTEE3icj18f8B6fwBriPjxwwnviIff5hA/4UUnb1jW3etvcNGDLv3HM",
	"dW1F+3/lSBxl+qtbvuw4tqNtb2/rWs10q069CQc/1UFYAXaBnwd40Y7OXNPw3LWq3bI8xvt8As854AO4",
	"jPf4IZ/CLWyxVPqQ8QEf8QFzTMszGsEt+3zKR+KJeMR99VlFPOHnlmc6ltGgM5xGi3X5hDUTHxFT5M+i",
	"w6cL8D84+lQ84iP4JxxBdHiPD0FxfErn5/uiy49Idb54LJ4xFNUh3soP+Rvun4lSfuAT0QXpo6onYk/s",
	"MdzbgO/zIe8x0UaV9fkAbQvW/Mr2PrNbVu1UErJsb20d744J50ep6B4u3ec97vOx2OVHcG5ftEVX7Ig2",
	"SQut4ogfwJbPRAj/0OKrtn3FsLak77unEopn22ubhrUVRAA3LpxXYMjiEfgwHzM+Bvflr8F4VH+Z8r60",
	"oD4YGXgN2c8xGtWu6PCh6J61AcX3Jh7yHgYWdHBld2KX/bLznOFHn/fFLnggnzC4m49hp2B2HVID7/Mh",
	"H7DrV64v4HMP4EysAM8Tj/FUPbw6Cl77eN4e4wP6AyqzLe6HN2NYuH7lejEtIgiCYz7lb0Cs0h9hExMZ",
	"JhzTNa3amrHumc6aa1Ztq+aygmjzcYn2DEGtk4xdcuM9iiy/tYyWd9t26v9lns5tWuoDYsbxVxKA6GIU",
	"bYP/9qLjocwe8IHYw4NHoV7GFrDjI9AYeniH+xAdMUAfQVSa8iGpqU/new3hE6FlyH12UW4JN38m1vQC",
	"j9DF/3d4nw4VRHJQjUQQ2JO6vYwT80FJ2w63hH55qVGXQk8s+xOaoc8nYDrxgMf4H2A/9Ec+EN/zAcpz",
	"RxX4MRnOlFBKdBlJkvvie4lIBRTbaz4gYcL3YoePeQ/VcLm0eH4ZTPMVRXnppqINz8AgBLeiY+0Ep2OF",
	"u6ZTX99aAAvRWd1ds8z//MRzWmaRWcamGeAGRS1QHiJ84IZdlPCU+2Ww4bjQxVPxmPtw24CPERBCQtAj",
	"hYAmDtFR4byPxDMEj654mrlZ8ZQV0A/RRdCEJmIvFB/wDLztkF29uHrpX1m56djr9YZZLGm61nTspul4",
	"dWJZVcc0PLO2ZmSp8TmKk6JAH58Iu88RHx9GSgdg07V129mE52o1wzMXvPqmqemat9UEN3M9p25tgInX",
	"axkr/4kAIbAQQE6yx1nLtFr1WtYKoL3MNVAX8eexHJchG0SuA5GIiYdEPA6Rc6nyGEiuiOwvwJXYIhAl",
	"pkw8Qv/vsSVWyFBTGLJgo/g0CFPGvS9Na8O7ra0sViq6tlm3ws8ZB2/etq2sk/858Ky0X+X4UonxP4k2",
	"2Zp4Ag4VOesQuBaL/LHE+A98hP6B0U88APfrs3+5vBoeEbgmmG8fDegxuUHo+2DPAaEWTz/GaDkST/k+",
	"kWnCvAPUD7jMiGi12BP3dXjwABnsGC8mKgYPgq8QHsUD4Mg6hO/nfMIKGHxH4ili7V5CJEWGgmgDgEIk",
	"Ek/lPgvXFiqLH+nsq8+uLSwuJlT2wUcXLlxYPLe0/OH5j8DlDA9orLai/fuNGx98u7hw4eaNG7XvFvXF",
	"5e3fpC12W9eAt9QdwLZvNTRqUqWu+uvN8Eb71u/MqgcaD5l2klWgqCYQssQO5StEk30izRFDHWTECITM",
	"jCDfw+eA6CHioIz4EQkMHjeRuEfQHVsExXduCUL0czJGebUvrxa7K8xtALdtNRqYuPiEJWA3+0gFZGo1",
	"RkbZKeqsZrduNcy1W7Z9p25tsAKaUoBjE1Qu30fvnIgn5M7onG9AFAANQD56RZ0WrhpW1Ww0zBpykxHx",
	"I7gCNwsRGt1adHE74+A21zMcL3aT6MoV4OkofQoPo6LOjIZjGrUtdTF1i3RntCr+BzusW3eNRr22Bqoh",
	"6Sip4FFZBqNnfIgiP2Jfr14FWVNYHSMWBhAcetoKq9fMzabtmVZ1a+2OubVWta31Rr3qxUXJIndhwOIP",
	"ELtfo38FFsXHsNxfJe/DwEF2ByouYzr2GALiClPydFZYrlSKOlO5GXy3WNTZuu3cqtdqpgVfLBV1FuY9",
	"8MVyUWcpzs8Ky+cuoKzUHJIVPrx3j9zVam2Cf4Vmpula3IQ0XYubQvCFVLKmaykFarqmKgc+5khV0xNF",
	"igQnDY+s6bEsLyu5SeTJN9VgpJ4vBRE10zPqDTcTJHzU0x5inMpkfdXFp+IhZRAyxyMOjF8gxzzgI/C7",
	"A7y4h6lJGCwgPkOeReYgayOUWsQQ02cFPDzyYpe9/fl8cYWlaxmAQ6IjurA0bJU8/kDad5cfq2Ua2tfl",
	"xfLlc7pEc8AXwp8h1j56eOXbv/NXatTh0xX2VRh23o5YOfOSKxTIwNdGskgEeZP4PUbJ45AmDPng7Yjx",
	"faRrxFbD7AulPqTAwWSKkg7Pxl2j3jDAbGVpZsM0MjEANxQQGFkWIWIlQ+lJN0wUMJDyNBGW+RTZKaod",
	"wvZ9iHaQLIM5/AOrxjE24jtg+xumA9YciQJrUfOFILU490Bkk+MAqggKFDST540Qq5xKzYGgRGgVO8u5",
	"9Fm2M8A9TFJTp/pZRt0+iDDukgT0SS8DUOH76iH8BOl8lYu08aIfIXNpLouRwTA4QxZ5udpyb6/ad0zr",
	"/5sN0zOV6m9KiROxB7lBfjLXbLm3F6KMFpypKy+Zhgl6D2lI5TxiVZT8KhVc8Sygpf2QGEKgkVlgn/32",
	"2pfx8BFmh8e4p10yfgDzttjF1f1kOdhnsY0i2yUyLYFcVlaewmpp/282DA9yoAxBvQQeLjoRo8+UggqG",
	"dRvgxLBqjl2vxXGE/pRCEA80lrF2JFDSRRet8wBdaBQEe+DrYjeqlUP4P05sesqPWOHi1a/c8meXrhTn",
	"WxptSI/kMtPW8q3sLxmJ995JDSsKgJShjyX+EcQFZvd/ujwLXV4z1x1zrjp/jMqJMpxDeJtg1BxFntjG",
	"INemksYxnzKHnq7oXHQp+8tSoLx6LU+Sz2fUB9Mr6bJySsWjpHSVelXUnMFHzBdsfJ/ZUkVJXrJr5jsJ",
	"VS06iy5kHkHRuScvmeSWHzIc4uxKGO8vQ6dNzhUiNTczDvMiKnrjAZTKd0x+JcZ/YDKFgwxRhbypLDcd",
	"sVtG9Y5p1RYCTqOWcBkZS27xpa9U4NHkAtCnIkG8n6DUGbG1cBxWvrCfA1eetJgQnVLJGGYfM/N4kkfn",
	"bgcE2HTsWqsKC2NywEeQZAPuq+cbAcEQT5L11KyHMllKT4k1fICazIhu3BDJBpMmWPtuWT+fZXlgeOn2",
	"STYllHvGXEupXLaRZ3f5BIStNGrUfssg6GUrBRQsR6f8G0sDTHTxSSOsaE+Qq5yvAK16hgL2wx5QkOOp",
	"9YRfHvzAls9diMnlfCWL33teY8aRX1FuwfgbtIkJFaVl5OnHDs574n7+1pcqFfYJ+5ARaosu8HVsczHJ",
	"x/yQuw3C6tYEETEV3amvqZxsqVLJpPsx2FPOmaPxrGiDCHjVqDuZ9AGHA9gX36yq9GUqBRNiXoBszKhW",
	"TdclgMjlxLGOVei6QV/xsexjyBGIWGv1YxaDIJRsZn05VnbH+Fg2Wt7tsrw9XJTu7QaaIfI1RZ88krMR",
	"YpcVcAedgM5lILh67rQcv/hmVUpGkWKJ8Z/QR6aY5k7RAPuiizUu4EU50pvfAszwf/Nes+6Y7lrdOpkL",
	"pHab7Q0xG71QyXS/OeTmWoq/hMpJUS1QrGp2as/q6+urcR3LKvEIZZWQrbgvA8sg117itaRSLvFdo68z",
	"2O+AH8dyNJVlf2oajpkoucnv5vGGmKklxRvbVEztWa7/b8gFZ5O1l1hY78hK8RtqsSHrjZM07PZhq7+c",
	"2X3ck+lyIGSkP0ySCyrMMfF7lNc4aHP58fYpGGdfMosJn+rSV4N2QdQ9lrwWO3KP5Q1BRzXwrWmwmOiG",
	"HdZDROc2gNiEZjbSHoid2zBPo1CR1a2bEj7mN1zR7w8ULh8eGySQ6O7p8m9siV2/BHngYvE0LGlANIcV",
	"ln/Z+eN5hor5XuwU0+ziHbjFPxHb1klG83zhxJz7ONc5QsegTr/E0VkYSnXvntrSUg0qhFj+fK7xFWJz",
	"CNL2fFbFyYsSzSXMHj6AM66EfnGKqQFWSBss46+yHTLhvXmJBqSLyjbC9t+YUTkfvxpn+EU4cTJrHkbO",
	"pWzrGkkvrX4Qp86wDzFKzC6cos/PCoF4M0dE+FStdNyy7YZpWCHquPNOE7G6zOoIMEQplvC8aa/Y1jXX",
	"rLacurd1HZ5L4ryFOAWcI/r0WTBO8cU3q5p+EvoTFX4ichNN2yhwHi9YxFhBjiFmUYGXpyNTK4xQmd1o",
	"VSpLVRV78RvsrKDMUUsJBL/teU2asKpb63ZGPElNNWGTg2qGSUCZP94E/pEbkcBLZGNCNowIOscsnO4b",
	"s4Js+f4sBwifxLNQygkh4Fy8+nliRkupX1Nqm/uNDzgrdlH8Q9ncHvAJf70gHsiFdrjP3v6d/wEQmA9F",
	"++0IfaHuUZvhp5y7EvfgLiH+oq3q2l3TcUnwi6VKqQLOZDdNy2jWtRVtqVQpLRHM3EYzJwtq2Bt2C2NH",
	"084tZskBLDmXJRtwXfGYZrHCIC+eYkidUCOfJk6CEbaMOh4ECGwqUTc1rOClXEnaRkaW6aOyRDvonxV1",
	"hjBCian0New23ZdwlbENDKvUM32NVykcPe5mGgrUQc/5vKataF+S9PT4kP65ynJmfyYQEyWDoVSRPIOy",
	"liuLeWEvfH45NuSJvep1o9Xw5t8YnzvH2Nfa3DScLZzQDkQEZmhsuBBI0apuwoUkBaxyR9G5hv2o7EYU",
	"4pW0luxRvZO2ojIa2vhJ1aofzm5SqklzGIGRZNflyVIq59+pyZUYv431vJBwdPgg1fw6eYtrEs5RS5DE",
	"KaS5ja+4SVKbMOzkaASOput9ate2TjAVfLLh2pyu5HYcjIFQbJ/EOa7GrQF0hufHgaICRpKMCR2FqyhD",
	"QSrRC4eKTu1ey7Td2TeF7yqcmT/+TeqfSo4JZ0n7qJ4Xvf+SZGfB5GbnJM2rmV28CAZkGI4DerwBLOdN",
	"1CpyZhsQ80YFRrmvdKNfxgqvmBUDwh/KXIN2NJaja2omggQ6bUKEQSm+JSOMxKWh6MLaL2hYJ8HkqVAs",
	"p8fpDSPKrZPl5XheVMi6JCXqYtq5r5kbddcznV/Nvc/asWenDOWYMp7xCXlgZb4zKe/F/c8C6Y/55zuZ",
	"K4dwK0nHDGr2gu/LtFC+TwR2ePBOvVSl+dinVgbVhLuShbEPgpuSReKETUviVaSZaHXMUidYxpRX7YIP",
	"YoE7VuiORsXzto3dkcpiiV1Mk8VU1jPlw+yavCyRpV5y6gUvzCXfesnyyKjN/p6cMauTfyJ/rJzZFtRs",
	"O+P1vrAFH5gSDRlmV4X+WXxaFga0lW9vxjz8RRiiCJxV2qLUu2Z6Np5qIahn5rl3vPNK7p2V4h4p7baZ",
	"kwSUSGGBVFavFnNGxcpBsRuAXClw/YTrYM2PMnIJx1Mir/s4ouhT+0RPlICpQU01a+VNBulryY4Fwv5H",
	"xdIN64aFrxr38CWGESYFU9or9ahlqh1r0UdNTnE/Guib8mFx5Ya1wGbWbgn9lRwmTAMySrrBO3rpwZAS",
	"lmThAAtsdfXLeMVU6WXO7riKNiuHTdfix2oNKZkQU01lyg9uWGxm5zX2UhcLZ+SfiU5shJ5kv5DkXZkN",
	"7zkt8xO97gjbntE4Z6IN59+PeuezXgOV3XN5AmXAKHjbT3klFC35IULQKDnSAdgh2qHfEVaEHsZ75WyK",
	"fEjO5qMpSZWc8NXS/LdKg1OFKXBqmJYPQp3RFWQFEfcech/9PwgYfdEO3vruyyHfaE5WbeSEgUipSheU",
	"F1PPVSrgWiyfIB+nX4hVR3oUw84yjhLjf5Rv8lMxcQ8Xi58Nq6ck0l4YmMZBYi0z+1giMgvY0Yshdl+i",
	"Kd33g+2pebJfGdqzhrGyQJ4iP1g7SvgR+XrKNE6L7ucuzL8l+RL8ewL4H9PxS3pLTvEZ0Orr1avFGZCv",
	"BNwZiK/+oobE+6Cxmdk1itj6zOGVJJUvyiLaFCvyo0QVXEah7/FtxdfylV+lPSffEM3pZ+f2lQt5zey7",
	"bm4jO7897vPJaVqFWR1CYjNn2gn8eMaJYk21dvQmdsC3BqJDnOcFfx1SIkL4aQyloh9cwNmWPkrgQPlR",
	"AGXO5ECyL0SgPYqVK7NgRK3uDBSCmVPdJ5wYZGRMyXG5XbmLwMNKLPGTLWFmmHpdT+6BUj9kRuBOn6iU",
	"pcRm/lSE8hsVfKBO2MVDP7XK33PkT8+m/MqBP2MgICvu/y0K+EHJDQ31Y/XHAJSm8eyecE4Q+F+AGvE5",
	"ooMEcsj4fQTUpTxLRsF4bAaWxFeP96m/vbkN2zGdu6bj4l8TdbhovDf8hRQMEuhdPp8sQBRBd34TdCc0",
	"XWs5DdnmdVfKZaNZLxlN897CHcPx6tZGSc6ylO8uatt6csnrnrFRtzZwPUxT2vIl3ym9aDVvNZfuX5i5",
	"6s1QTO/Wez6moqyS+eGYFPt69aoW/DYCCX775vZ/BwAA//8+G8f3kksAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
