// Package profileapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package profileapi

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for ErrorCode.
const (
	ErrorCodeAlreadyCancelled       ErrorCode = "already_cancelled"
	ErrorCodeBadRequest             ErrorCode = "bad_request"
	ErrorCodeDoubleBooking          ErrorCode = "double_booking"
	ErrorCodeForbidden              ErrorCode = "forbidden"
	ErrorCodeIdempotencyKeyConflict ErrorCode = "idempotency_key_conflict"
	ErrorCodeInternalError          ErrorCode = "internal_error"
	ErrorCodeInvalidCode            ErrorCode = "invalid_code"
	ErrorCodeNotFound               ErrorCode = "not_found"
	ErrorCodeSlotCancelled          ErrorCode = "slot_cancelled"
	ErrorCodeSlotFull               ErrorCode = "slot_full"
	ErrorCodeSlotStarted            ErrorCode = "slot_started"
	ErrorCodeTooManyRequests        ErrorCode = "too_many_requests"
	ErrorCodeUnauthorized           ErrorCode = "unauthorized"
)

// ChangePhoneConfirmRequest Подтверждение смены номера телефона.
type ChangePhoneConfirmRequest struct {
	// Code OTP-код из SMS (4–6 цифр).
	Code string `json:"code"`

	// NewPhone Новый номер телефона в формате E.164.
	NewPhone string `json:"new_phone"`
}

// ChangePhoneRequestCodeRequest Запрос на отправку OTP-кода для смены номера телефона.
type ChangePhoneRequestCodeRequest struct {
	// NewPhone Новый номер телефона в формате E.164.
	NewPhone string `json:"new_phone"`
}

// Client Клиент сервиса. Аутентифицируется по номеру телефона (логин в формате E.164). Сразу после регистрации (verify-code, is_new=true) name ещё не задан — пустое/отсутствующее имя означает незавершённую регистрацию (дозаполняется через PATCH /profile).
type Client struct {
	// CreatedAt Дата и время регистрации клиента.
	CreatedAt time.Time `json:"created_at"`

	// Id Идентификатор клиента.
	Id openapi_types.UUID `json:"id"`

	// Name Имя клиента. Отсутствует у только что зарегистрированного клиента до шага 3 (PATCH /profile).
	Name *string `json:"name,omitempty"`

	// Phone Номер телефона в формате E.164. Используется как логин. Владельцу в GET /profile возвращается полностью; в любых представлениях, видимых третьим лицам, ПДн (включая телефон) маскируются (R-017, NFR-11).
	Phone string `json:"phone"`
}

// Error Стандартное тело ошибки.
type Error struct {
	// Code Канонический машинный код ошибки (R-023). Доменные коды: slot_full (нет свободных мест), double_booking (повторная бронь того же слота), slot_cancelled (слот отменён клубом), slot_started (слот уже стартовал), already_cancelled (бронь уже отменена), invalid_code (неверный/истёкший OTP). Идемпотентность: idempotency_key_conflict (повтор ключа с другим телом). Транспортные/общие: bad_request (400), unauthorized (401), forbidden (403), not_found (404), too_many_requests (429), internal_error (5xx).
	Code ErrorCode `json:"code"`

	// Details Необязательные машиночитаемые детали для динамических сообщений на клиенте (foundations §6): например, актуальная доступность для E1/E2, чтобы показать «Свободно: N мест» / «Свободно: M комплектов экипировки» без разбора текста message.
	Details *struct {
		// AvailableRentalGear Сколько прокатных комплектов экипировки реально свободно (для нехватки прокатных комплектов экипировки).
		AvailableRentalGear *int `json:"available_rental_gear,omitempty"`

		// AvailableSeats Сколько мест реально свободно на момент ошибки (для slot_full / превышения мест).
		AvailableSeats *int `json:"available_seats,omitempty"`
	} `json:"details,omitempty"`

	// Message Человекочитаемое сообщение об ошибке.
	Message string `json:"message"`
}

// ErrorCode Канонический машинный код ошибки (R-023). Доменные коды: slot_full (нет свободных мест), double_booking (повторная бронь того же слота), slot_cancelled (слот отменён клубом), slot_started (слот уже стартовал), already_cancelled (бронь уже отменена), invalid_code (неверный/истёкший OTP). Идемпотентность: idempotency_key_conflict (повтор ключа с другим телом). Транспортные/общие: bad_request (400), unauthorized (401), forbidden (403), not_found (404), too_many_requests (429), internal_error (5xx).
type ErrorCode string

// RequestCodeResponse Ответ на запрос OTP-кода. В демонстрационной backend-реализации code возвращается в ответе вместо отправки через SMS-провайдера.
type RequestCodeResponse struct {
	// Code OTP-код для демонстрационной реализации без SMS-провайдера. В production должен отправляться через провайдера и не возвращаться клиенту.
	Code *string `json:"code,omitempty"`

	// ResendAfterSeconds Через сколько секунд можно запросить повторную отправку (по умолчанию 60). Более ранний повтор → 429.
	ResendAfterSeconds int `json:"resend_after_seconds"`

	// TtlSeconds Срок жизни кода в секундах (по умолчанию 300 = 5 минут). По истечении код недействителен.
	TtlSeconds int `json:"ttl_seconds"`
}

// UpdateProfileRequest Запрос на обновление профиля.
type UpdateProfileRequest struct {
	// Name Имя клиента.
	Name string `json:"name"`
}

// BadRequest Стандартное тело ошибки.
type BadRequest = Error

// Conflict Стандартное тело ошибки.
type Conflict = Error

// InternalError Стандартное тело ошибки.
type InternalError = Error

// TooManyRequests Стандартное тело ошибки.
type TooManyRequests = Error

// Unauthorized Стандартное тело ошибки.
type Unauthorized = Error

// UpdateProfileJSONRequestBody defines body for UpdateProfile for application/json ContentType.
type UpdateProfileJSONRequestBody = UpdateProfileRequest

// ConfirmPhoneChangeJSONRequestBody defines body for ConfirmPhoneChange for application/json ContentType.
type ConfirmPhoneChangeJSONRequestBody = ChangePhoneConfirmRequest

// RequestPhoneChangeCodeJSONRequestBody defines body for RequestPhoneChangeCode for application/json ContentType.
type RequestPhoneChangeCodeJSONRequestBody = ChangePhoneRequestCodeRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Удалить аккаунт
	// (DELETE /profile)
	DeleteAccount(w http.ResponseWriter, r *http.Request)
	// Получить профиль
	// (GET /profile)
	GetProfile(w http.ResponseWriter, r *http.Request)
	// Обновить имя
	// (PATCH /profile)
	UpdateProfile(w http.ResponseWriter, r *http.Request)
	// Подтвердить смену телефона
	// (POST /profile/phone/confirm)
	ConfirmPhoneChange(w http.ResponseWriter, r *http.Request)
	// Запросить код для смены телефона
	// (POST /profile/phone/request-code)
	RequestPhoneChangeCode(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Удалить аккаунт
// (DELETE /profile)
func (_ Unimplemented) DeleteAccount(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Получить профиль
// (GET /profile)
func (_ Unimplemented) GetProfile(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Обновить имя
// (PATCH /profile)
func (_ Unimplemented) UpdateProfile(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Подтвердить смену телефона
// (POST /profile/phone/confirm)
func (_ Unimplemented) ConfirmPhoneChange(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Запросить код для смены телефона
// (POST /profile/phone/request-code)
func (_ Unimplemented) RequestPhoneChangeCode(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// DeleteAccount operation middleware
func (siw *ServerInterfaceWrapper) DeleteAccount(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteAccount(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetProfile operation middleware
func (siw *ServerInterfaceWrapper) GetProfile(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProfile(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateProfile operation middleware
func (siw *ServerInterfaceWrapper) UpdateProfile(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateProfile(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ConfirmPhoneChange operation middleware
func (siw *ServerInterfaceWrapper) ConfirmPhoneChange(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ConfirmPhoneChange(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RequestPhoneChangeCode operation middleware
func (siw *ServerInterfaceWrapper) RequestPhoneChangeCode(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RequestPhoneChangeCode(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/profile", wrapper.DeleteAccount)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/profile", wrapper.GetProfile)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/profile", wrapper.UpdateProfile)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/profile/phone/confirm", wrapper.ConfirmPhoneChange)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/profile/phone/request-code", wrapper.RequestPhoneChangeCode)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xaX2/bxpb/KgPufZBwqX+246wV9CHN5t7N3c29QZyiD4lXYKSxzUYitSSVxlsIkK0m",
	"cWDXbroBWgRoi3Qf8rAvsmLGsv4ZyCeY+Qr5JItzZkgOJcp2Une7C9yXxJLImfP3d875zXylle1a3bao",
	"5bla8SvNoW7dtlyKHz41Krfpvzeo68Gnsm151MI/jXq9apYNz7St3BeubcF39JFRq1epeLJCtaJ236iU",
	"HPm+rtWo6xpr8D37kfmsy3zeYiO+w3zCTliHt1iHDZnPt3iL7xB2xDrshLfYmG+yTpawn+Fv8Rbf5Vvw",
	"Vp+NeYu3mM/6fIuN4FG+xXdhOR+/PmQdNoI9+GNYcMQ6/Cnz2Yj12HFWa+qaW16nNQNE/oNDV7Wi9g+5",
	"yBw58aubu+44tqM1m01dq1C37Jh1UPyjFCEpkAI/9/Chlk5canhuqWw3LI+wLhvBOoesB4+xDjtiY3iF",
	"FLLZS4T12ID1iEMtz6gGrxywMRvwXb7NfHWtNGp4zbZWq2b54xzoVm2vtNqoVjXQ3DPMKoaF8dAwq8b9",
	"Ki1JQdao4WjFgq78goJoxXxzwvEdwrp8hx2glUbgNDYkfJMN2Fg4FdVHT7IOfrvJd+GBLhujpoeBP8F6",
	"m3zrgvzY4S3eBhNidPhg6RHrojfBEyMQh7xvvUAB+dZpEgVeEl5nfdaB6BSP9EFfdsIGMmjHrEv4N6zP",
	"euyE9WSI91mPpIJgZwe8jb+P2BudhB5J6xAkIMIxxvU+QZuO2YjvklTFboAT7tv2A9Nag2dPYD3YEGJV",
	"PA8GH6LCHZIyqg41KhulsmGVabVKK2kCSoCCsZfJjQqt1W2PWuWNzL/QDcI3CTsE47E3ENIEvAh+Y8Op",
	"0DejV0sP6EapLGNTJ7cz+bk5EbA3LI86llEVzvqYqDXlCiWKS8QC8DVokYF/UCu+DaKKoMOA6wPSsLF0",
	"HZj+WISlz5/x5wSj9kgY5Ii9Zf6FRN93bMTbABfojBHfF97ZRvP3WQeCDSKhy3oIhrDnHdu+aVgbEp7d",
	"jzKUZ9ulmmFtBCDtxm31CgKAb4uYheiGZH0D5lL9OmZdabMgvHrCYidoxh2+xfq8fdEmi8vGn7IOYj9i",
	"sCId3xE5e4K27fIdkeEitIcgqUiDE3SsyLzlm8sZXPcQszMF6/FnqFUHn47qywHq2yGQ7PADfOCb/HH4",
	"MubW8s3l9LSJoE4N2Zi9BbPKCERMlEjuUJdalZKx6lGn5NKybVVckuKbbJgVMncRhyZyTAreEbn0mWU0",
	"vHXbMf+DVj4qQhrqArHg+EUYgLex0G1CxHYi9dBmT1iP76PiUTWW2XTIfHaMGN8V4QIFDGvoMUFU7As3",
	"dYV+b6DCSWj0yVUpEgp/IdH0E6rQxn+3WFcoFcL4KCzyIJMqXoLGrJfVmqFImJfX1g1rjd5aty0K1dh0",
	"akpTNSEJBMmhdG6LvUVDiYIEnocP0FJg1cQnOgHe+vxr0ShkNV2rO3adOp5J3ciXk1v97c4tGeag6BFE",
	"KUktvG/95yJBz33NW2lYKwwKrTA3vwCLGx7gq1bU/u3evcpXC/pi8w+arnkbdWwZPMe01sApFv2yVAel",
	"E9T8EXMBvB3pMqUJuB/+5i02xBrqk+vZwuJCXKo/Xl5aWgLRLi1enpTuj3cLmaUVkLKgFxaSxGzqGoCf",
	"6UCC3FVk1oXZVsI37Ptf0LKHLVXkT+nIa3aFzvbp91GGCkCIQw5vk8gX8OshG/D9X+Hv/9+GT7R41ZSw",
	"NaHOSwRysNLWZJEk7FvIaPEjxDPrYVy3VMg6EdArDcHb06ZIIfBAazOaZRYA91eiM5CFDvtZxHMfXsXS",
	"1ArwgaQeUsdc3chAgOnEdEsW/fITz2nQNLGMGg16DdEJA/zhGBMUsjZi1Jj5OQijOGzxPf6M+aJ7HWIT",
	"EU49HQFpgGVHGHeg7zZ/jg1Hm+8lCsv3SAorGRYZBOER3w/NB8MUvnZEbl29c+2fSa7u2KtmlaYTQMih",
	"hkcrJSPJjS/QnKKOdnFFkH6G+Vg/croI/1XbqcG6WsXwaMYzazQJj8xKws4/CIQNIkQ269DnnrJNo2FW",
	"EhHPqNHEPdAX8fXIjKIjYhAHOkAEwp+KZvUIRxHVHsG0EIxR2JnFNgEoGRO+jRW0Q+ZJKsFNUUKzH8Rq",
	"UOiNR/9KrTVvXSsW8nldq5lW+DlB8dPQ5gMhhrAf+KaINb4LCRUlax/6cxLlY5aw79gA8wP7B/4E0q9L",
	"/nz9TqgiwRHpCKMKurhOLPchngPWgO9dwX5jwPfYgRjWRNd4KGfRLg5tI2hq+GMdFu7hmD7Eh0X7Dgvh",
	"FITt6RPWYUMdGqAXbERS2L4M+B52q/sTJkkTNMQmtKA4iu5JOVO3M/nCZZ389U+3M4VC+jfEYAzqsPpF",
	"+ZqEyOF0NtmXo6lGAFm8JUgZMVr5YtCKppreeRsV9hJXHKPpAXHQRlDBwGDbOBmLzjFoZ5RN0Hxz8wDR",
	"L0Qwyqd9+TTfKUZDNbIzZ0z3aZ3Ep2uSShquo2Ec0xmT861o4wTV0UnLaT6cuLG7H4gJI5zNAaExrXkb",
	"xRkGr7me4Xixl3hb7gCro/UFPAzSOpka70lKFVG8qTACyAqkdWJaD42qWSmBa4R1FL7rOCfB6Dnro8mP",
	"oZMBWwtYHWItDEpwmGlFMosIiJuSROlyCssA2/0iJycEDhF34OIcjvDPABCLRCEjSWohn0/rRJ1u4LtC",
	"WiertnPfrFSoBV/Mp3ViQWzYDQufWEjrZGpqJqmFuSW0lco7kNSlR49EulqNGuRXjE2LhZCma/FQCL6Q",
	"TtZ0bcqBmq6pzoGPM6yq6RNM7MRUF6qs6VqoLaBFAj0wwa2sqGCk6jdVIhT6MIFDBT/tY41TZ0FfTfEx",
	"fypmcOwOduQUKVnCXtA1IyKPkIBVwALweZONZThIAlj24mrF9EkKlcfJ0iXvXi+mi2SasIU6xLd4G7YG",
	"UUXGH8r4brMTlYsWcl0v5K7P6bKaQ30R9aePBG8Hn3z33+yVijpsXCR/DWHn3YDkEh+5eX5S8d2AsANs",
	"10S3GvIXaPW+AA4ih/xpeJ5B+07XABQoaGB+FQuKBTiw8ngCltkYu1N0O8D2Y+Rrt/DFX7NrvMZG/Q7E",
	"/hp1IJqneO6zjBBQw2cpJGJyGJQqUQqUaib1jSpWborcggYlqlYxXeamdWkmFPeQ5pnS6rVE3S6YMJ6S",
	"otBPZhkUFXagKuFPNJ2vTuHR1ZMNUZmzZ3YxEgwDHZKal9jULo67EnT9KeLY0CkK0RYb2KENJbLeQTlV",
	"p5Wx7M2PyX2j/IBalUwQACpjRLC6zu5UuwrhB5boBhYSHVWcvlSGMmQyT8Ix4RgBs/VxFFEIr6ermaie",
	"BJ2Z4oAB645daZRhY0RSNoCOBFofVb8B38dWfWL4TFqUSOZuyqzhAiry8/Y01XVp8QPIriS2Njl/pMxY",
	"mJQxbxNBqQ2tc4wXVundXnC6qXSbOLtPEUrYR0FbN8Q9nmIHDeP8Yh76pedoYD+knIOCqDZf7598Rxbm",
	"lmJ2WcwngaHnVU9R+ZUAYuh+e8hG9EhEdXVjirMOfzxb9Pl8nnxCLoF1euLARLLqRHShzA8Pd3vhKDBC",
	"3nmKbIbnYprN5/OJ2Kgii6rnDI8noc1n9Yrh0VtiHv0glpAdYFaFgyeequAjX7MeJEMC9/cBFMSFDP+T",
	"PB7sP22Fpq65tNxwTG9jubxOa0LY+9RwqHO1ASsHn/4UkCx/+fyONknU/+XzO8Qol6nrZiIaXhcnyhA9",
	"z5XZXnJwt/62fIfkoN/NKbSbOLGJ7DuD1IredeiqQ931+GlGtN/Z5xRF8inqR+418vn5stCi5NkPqIXf",
	"YL+FhwZ4cwKfjYBm3fPq4uTCtFbtpHMDJSx2JxxdJCGCDJEzbOkhu4xAKf/sxb6eZmxOBMEEQ3M7PDPQ",
	"IVUPEfLDGO2wPnZe7ZDrei3P5+KiSQyE2fjqrRsTBK6EPvzQU0vw1Dc+O4I5Hr3Ql5MvHpdn+BO5UYv5",
	"0Dx/y05Eo/tugI2E6YnYfznjrYl3UMr3rRdEJrOmaw+p4woXFLL5bB7y3a5Ty6ibWlGbz+az86KIrGPA",
	"B6yUcGCVekm5+l9nmBNjF08gsdsaBe2k6J1iV17ibGAKOzMA/AMsGH1YC7mpgF3K4X9zV8jytduZfP4y",
	"TEDZeZ1cvZbJ5//xCoEvl3JISEnsFVkmOTLw3H7xnpWRExLrsW4wyEmyAXpY1zO8hvuJUfbMhzRNpMBt",
	"pMxU5kucqkYd8lvMuT1oyIL+Rxoj3usz/55FkucJUXBgQTkTSi6GP75yz0LBRaZso07Qsvq5BL58QqOI",
	"n8LadDTJ4KH8EKUDHEp7OKeEWiLfg25I63gYgdJvsjF/LGmN/ehheTbU5k8BfFgnJ9meLVkDe0LNgC/q",
	"BGp1IblEhm1C+sBDil6KPCkJdQrCQm6BmY74jip6Wif1xuSDARpEQmfvWeyFWoJlMx9EI0o9ZOMrov9I",
	"Pv0M+yBBB3TV9jhpjOfbskGCIJfRjLMQFEsE5BsVraj9Eybh1TJemBJFPbr9NpdfSEjPb9VsJIJ56IRR",
	"oYIh39EVi4OkqsURZQEvFvKFWSfXoTi52Ek+0imrRqPqnf1i/DoNFuJGrWY4GyrUyMYyBjSAj8aaC0U9",
	"gLuVpq6t0RkHOJEJBJnQxhkw4VAiFT/fkOkoIWguwUl/pl4EuBMeyp/jWsP5bgfIM8ak6wGnFdff2YM/",
	"oynbYhDH4UCVdYYP64ZXXk/kLKZ7gmB4m5Wboq0U912G6Fula5ATmKAyohYL6jWmxW6Ct2Ptsia6S+p6",
	"n9qVjQvzdWJL3oz3sp7ToM3fJ95+UhrT59HpxsmZYZg/O5qUK72/b+RGSsrIxSPrxIht6mHnlMPzqVxZ",
	"3KMBEer2OS/ShCfgCTcglBBOnAwIbpswQMVjV17vEVd98JbIbxTAs68U/T2KzxnFC/mls18Kb09fKGBH",
	"cXkogz+87DN9A+WcGSGjLBMweTPS4pcYPOOVkvA8XdwS5t9gfR6CKMqQeJKcTwGTFmWPvEom3kpMttTs",
	"fkw6VUmga4LO/Y2TKOEe1/9yIiVx0klZ9RJ5Ld7Gs06fbwuWMEaSCt50pv3/TyfZwtw5Xpi8+3xhyfn9",
	"NNkao7+VO3nnS1OF99KKd+OM192V5gr87Dykjou/xl19K2LEwzvMSJviYbvPRhkYu/BM/G0wJ2m61nCq",
	"kjByi7mcUTezRp0+yjwwHM+01rKS8cs9LGhNfXLLZc9YM6013A8J1U15iWAsDnLO2s0V72dO3XUltNQH",
	"sVhacL8qtG9zpfk/AQAA///1gnTnvjQAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
